%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Funds": "Aditya Birla SL CEF-Global Agri-Reg(G)",
    "FundManager": "Milind Bafna",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "9.8",
    "ExpenseRatio": "1.73",
    "FundType": "Open Ended",
    "InceptionDate": "7-Nov-08",
    "BenchmarkIndex": "S&P Global Agribusiness Index",
    "NAV": "30.78",
    "52WeekHigh": "30.78",
    "52WeekLow": "18.14",
    "Return1mo": "1.88",
    "Return3mo": "13.5",
    "Return6mo": "36.85",
    "Return1yr": "60.45",
    "Return2yrs": "15.02",
    "Return3yrs": "10.55",
    "Return5yrs": "9.01",
    "Return10yrs": "5.8",
    "TurnoverRatio": "4",
    "NoofStocks": "21",
    "AvgMarketCap": "11480",
    "LargeCap": "3.36",
    "MidCap": "-",
    "SmallCap": "4",
    "HighestSector": "Chemicals",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.41",
    "Sharpe": "2.52",
    "Sortino": "4.38",
    "Beta": "0.25",
    "StandardDeviation": "19.5",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D"
  },
  {
    "Funds": "Aditya Birla SL Intl. Equity Fund-A(G)",
    "FundManager": "Vineet Maloo",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "110.4",
    "ExpenseRatio": "2.5",
    "FundType": "Open Ended",
    "InceptionDate": "31-Oct-07",
    "BenchmarkIndex": "S&P Global 1200",
    "NAV": "29.93",
    "52WeekHigh": "29.93",
    "52WeekLow": "21.16",
    "Return1mo": "7.82",
    "Return3mo": "8.94",
    "Return6mo": "17.99",
    "Return1yr": "40.35",
    "Return2yrs": "19.42",
    "Return3yrs": "17.22",
    "Return5yrs": "13.63",
    "Return10yrs": "11.63",
    "TurnoverRatio": "105",
    "NoofStocks": "70",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "26.46",
    "Sharpe": "2.17",
    "Sortino": "3.51",
    "Beta": "0.16",
    "StandardDeviation": "15.95",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 90D Nil after 90D"
  },
  {
    "Funds": "Aditya Birla SL Pharma & Healthcare Fund-Reg(G)",
    "FundManager": "Dhaval Shah",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "454.9",
    "ExpenseRatio": "2.57",
    "FundType": "Open Ended",
    "InceptionDate": "10-Jul-19",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "16.78",
    "52WeekHigh": "17.07",
    "52WeekLow": "11.9",
    "Return1mo": "5.2",
    "Return3mo": "0.06",
    "Return6mo": "9.46",
    "Return1yr": "40.18",
    "Return2yrs": "-",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "48",
    "NoofStocks": "25",
    "AvgMarketCap": "43484",
    "LargeCap": "67.4",
    "MidCap": "22.78",
    "SmallCap": "7.63",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "23.44",
    "Sharpe": "2.14",
    "Sortino": "3.71",
    "Beta": "0.32",
    "StandardDeviation": "18.39",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 30D Nil after 30D"
  },
  {
    "Funds": "Aditya Birla SL Resurgent India Fund-4-Reg(G)",
    "FundManager": "Chanchal Khandelwal",
    "Category": "EQ-MLC",
    "RupeeVestRating": "Unrated",
    "AUM": "297.1",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "12-Jul-17",
    "BenchmarkIndex": "S&P BSE 200",
    "NAV": "11.21",
    "52WeekHigh": "11.27",
    "52WeekLow": "7.79",
    "Return1mo": "4.09",
    "Return3mo": "19.13",
    "Return6mo": "25.96",
    "Return1yr": "16.29",
    "Return2yrs": "7.31",
    "Return3yrs": "1.56",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "6",
    "NoofStocks": "46",
    "AvgMarketCap": "84485",
    "LargeCap": "52.16",
    "MidCap": "19.92",
    "SmallCap": "4.86",
    "HighestSector": "Financials",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "3.93",
    "Sharpe": "0.78",
    "Sortino": "1.09",
    "Beta": "0.47",
    "StandardDeviation": "17.97",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "DSP 3Y Close Ended Equity Fund-Reg(G)",
    "FundManager": "Vinit Sambre",
    "Category": "EQ-LC",
    "RupeeVestRating": "Unrated",
    "AUM": "39.2",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "27-Nov-14",
    "BenchmarkIndex": "NIFTY 500",
    "NAV": "19.08",
    "52WeekHigh": "19.15",
    "52WeekLow": "14.45",
    "Return1mo": "1.43",
    "Return3mo": "17.25",
    "Return6mo": "23.79",
    "Return1yr": "18.34",
    "Return2yrs": "15.4",
    "Return3yrs": "8.75",
    "Return5yrs": "12.09",
    "Return10yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "49",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "10.79",
    "Sharpe": "0.76",
    "Sortino": "1.38",
    "Beta": "0.3",
    "StandardDeviation": "21.94",
    "classification": "Equity : Large Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "DSP A.C.E. Fund-Sr 1-Reg(G)",
    "FundManager": "M Suryanarayanan",
    "Category": "EQ-MLC",
    "RupeeVestRating": "Unrated",
    "AUM": "717.2",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "7-Dec-17",
    "BenchmarkIndex": "NIFTY 500",
    "NAV": "12.71",
    "52WeekHigh": "12.76",
    "52WeekLow": "9.6",
    "Return1mo": "1.43",
    "Return3mo": "17.28",
    "Return6mo": "23.98",
    "Return1yr": "18.3",
    "Return2yrs": "15.43",
    "Return3yrs": "8.81",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "49",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "10.46",
    "Sharpe": "0.76",
    "Sortino": "1.38",
    "Beta": "0.31",
    "StandardDeviation": "21.72",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "DSP Healthcare Fund-Reg(G)",
    "FundManager": "Chirag Dagli",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "1109.6",
    "ExpenseRatio": "2.29",
    "FundType": "Open Ended",
    "InceptionDate": "30-Nov-18",
    "BenchmarkIndex": "S&P BSE Health Care",
    "NAV": "19.94",
    "52WeekHigh": "20.2",
    "52WeekLow": "12.23",
    "Return1mo": "3.92",
    "Return3mo": "1.69",
    "Return6mo": "12.14",
    "Return1yr": "62.36",
    "Return2yrs": "39.13",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "17",
    "NoofStocks": "24",
    "AvgMarketCap": "32670",
    "LargeCap": "47.39",
    "MidCap": "26.88",
    "SmallCap": "12.13",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "35.28",
    "Sharpe": "3.18",
    "Sortino": "5.74",
    "Beta": "0.31",
    "StandardDeviation": "15.92",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 12M Nil after 12M"
  },
  {
    "Funds": "Edelweiss Maiden Opp Fund-1-Reg(G)",
    "FundManager": "Bhavesh Jain",
    "Category": "EQ-MLC",
    "RupeeVestRating": "Unrated",
    "AUM": "513.6",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "22-Feb-18",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "NAV": "14.9",
    "52WeekHigh": "15.49",
    "52WeekLow": "8.75",
    "Return1mo": "-2.36",
    "Return3mo": "6.63",
    "Return6mo": "32.65",
    "Return1yr": "70.64",
    "Return2yrs": "29.11",
    "Return3yrs": "13.86",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "114",
    "NoofStocks": "39",
    "AvgMarketCap": "26403",
    "LargeCap": "33.45",
    "MidCap": "30.27",
    "SmallCap": "24.84",
    "HighestSector": "Financials",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "33.26",
    "Sharpe": "3.77",
    "Sortino": "6.55",
    "Beta": "0.47",
    "StandardDeviation": "15.03",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "Franklin Asian Equity Fund(G)",
    "FundManager": "Roshi Jain",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "260.9",
    "ExpenseRatio": "2.74",
    "FundType": "Open Ended",
    "InceptionDate": "16-Jan-08",
    "BenchmarkIndex": "MSCI Asia (ex-Japan) Standard Index",
    "NAV": "32.47",
    "52WeekHigh": "35.51",
    "52WeekLow": "21.58",
    "Return1mo": "-0.39",
    "Return3mo": "-0.4",
    "Return6mo": "16.71",
    "Return1yr": "52.27",
    "Return2yrs": "19.68",
    "Return3yrs": "12.91",
    "Return5yrs": "15.51",
    "Return10yrs": "10.92",
    "TurnoverRatio": "33.56",
    "NoofStocks": "59",
    "AvgMarketCap": "87516",
    "LargeCap": "9.43",
    "MidCap": "3.63",
    "SmallCap": "1.36",
    "HighestSector": "Financials",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "17.92",
    "Sharpe": "2.41",
    "Sortino": "4.12",
    "Beta": "0.48",
    "StandardDeviation": "17.34",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 1Y"
  },
  {
    "Funds": "ICICI Pru FMCG Fund(G)",
    "FundManager": "Ihab Dalwai",
    "Category": "EQ-CONS",
    "RupeeVestRating": "3",
    "AUM": "605.9",
    "ExpenseRatio": "2.61",
    "FundType": "Open Ended",
    "InceptionDate": "31-Mar-99",
    "BenchmarkIndex": "NIFTY FMCG - TRI",
    "NAV": "274.96",
    "52WeekHigh": "280.75",
    "52WeekLow": "205.29",
    "Return1mo": "0.88",
    "Return3mo": "-1.5",
    "Return6mo": "17.82",
    "Return1yr": "26.49",
    "Return2yrs": "5.68",
    "Return3yrs": "7.11",
    "Return5yrs": "11.62",
    "Return10yrs": "14.99",
    "TurnoverRatio": "54",
    "NoofStocks": "22",
    "AvgMarketCap": "91252",
    "LargeCap": "70.28",
    "MidCap": "16.49",
    "SmallCap": "9.48",
    "HighestSector": "FMCG",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "1.41",
    "Sharpe": "1.59",
    "Sortino": "2.62",
    "Beta": "0.45",
    "StandardDeviation": "15.15",
    "classification": "Equity : Thematic - Consumption",
    "ExitloadRemarks": "1% on or before 15D NIL after 15D"
  },
  {
    "Funds": "ICICI Pru Pharma Healthcare & Diagnostics (P.H.D) Fund-(G)",
    "FundManager": "Dharmesh Kakkad",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "2213.6",
    "ExpenseRatio": "2.25",
    "FundType": "Open Ended",
    "InceptionDate": "13-Jul-18",
    "BenchmarkIndex": "S&P BSE Health Care",
    "NAV": "18.1",
    "52WeekHigh": "18.37",
    "52WeekLow": "11.62",
    "Return1mo": "3.78",
    "Return3mo": "-0.17",
    "Return6mo": "11.8",
    "Return1yr": "54.31",
    "Return2yrs": "33.04",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "50",
    "NoofStocks": "30",
    "AvgMarketCap": "32514",
    "LargeCap": "51.78",
    "MidCap": "26.31",
    "SmallCap": "15.69",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "33.64",
    "Sharpe": "2.71",
    "Sortino": "4.85",
    "Beta": "0.32",
    "StandardDeviation": "18.24",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 15D Nil after 15D"
  },
  {
    "Funds": "ICICI Pru US Bluechip Equity Fund(G)",
    "FundManager": "Rohan Maru",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "1282",
    "ExpenseRatio": "2.37",
    "FundType": "Open Ended",
    "InceptionDate": "6-Jul-12",
    "BenchmarkIndex": "S&P 500 ",
    "NAV": "43.5",
    "52WeekHigh": "43.52",
    "52WeekLow": "29.94",
    "Return1mo": "7.25",
    "Return3mo": "11.8",
    "Return6mo": "25.11",
    "Return1yr": "42.72",
    "Return2yrs": "25.41",
    "Return3yrs": "23.97",
    "Return5yrs": "18.41",
    "Return10yrs": "-",
    "TurnoverRatio": "52",
    "NoofStocks": "44",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "24.39",
    "Sharpe": "1.89",
    "Sortino": "3.14",
    "Beta": "0.25",
    "StandardDeviation": "19.37",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 1M Nil after 1M"
  },
  {
    "Funds": "ICICI Pru Value Fund-16(G)",
    "FundManager": "Sankaran Naren",
    "Category": "EQ-MLC",
    "RupeeVestRating": "Unrated",
    "AUM": "712.8",
    "ExpenseRatio": "1.42",
    "FundType": "Closed Ended",
    "InceptionDate": "11-Aug-17",
    "BenchmarkIndex": "S&P BSE 500",
    "NAV": "12.52",
    "52WeekHigh": "12.6",
    "52WeekLow": "9.73",
    "Return1mo": "3.64",
    "Return3mo": "13.41",
    "Return6mo": "20.5",
    "Return1yr": "16.47",
    "Return2yrs": "10.44",
    "Return3yrs": "5.56",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "40",
    "NoofStocks": "24",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "5.77",
    "Sharpe": "1.03",
    "Sortino": "1.55",
    "Beta": "0.26",
    "StandardDeviation": "13.19",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "IDBI Healthcare Fund-Reg(G)",
    "FundManager": "Uma Venkatraman",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "64.4",
    "ExpenseRatio": "2.46",
    "FundType": "Open Ended",
    "InceptionDate": "28-Feb-19",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "16.86",
    "52WeekHigh": "17.19",
    "52WeekLow": "12.13",
    "Return1mo": "4.07",
    "Return3mo": "-0.59",
    "Return6mo": "7.59",
    "Return1yr": "38.54",
    "Return2yrs": "29.35",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "58",
    "NoofStocks": "25",
    "AvgMarketCap": "49473",
    "LargeCap": "66.12",
    "MidCap": "16.77",
    "SmallCap": "8.26",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "22.76",
    "Sharpe": "2.1",
    "Sortino": "3.72",
    "Beta": "0.29",
    "StandardDeviation": "17.69",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 12M Nil after 12M"
  },
  {
    "Funds": "L&T Emerging Opp Fund-I-Reg(D)",
    "FundManager": "Vihang Naik",
    "Category": "EQ-SML",
    "RupeeVestRating": "Unrated",
    "AUM": "546.2",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "20-Feb-18",
    "BenchmarkIndex": "S&P BSE Small-Cap - TRI",
    "NAV": "13.7",
    "52WeekHigh": "13.82",
    "52WeekLow": "7.56",
    "Return1mo": "-0.41",
    "Return3mo": "3.94",
    "Return6mo": "21.2",
    "Return1yr": "82.45",
    "Return2yrs": "20.78",
    "Return3yrs": "10.26",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "0.61",
    "NoofStocks": "1",
    "AvgMarketCap": "916",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "1.31",
    "HighestSector": "Chemicals",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.82",
    "Sharpe": "3.8",
    "Sortino": "6.42",
    "Beta": "0.5",
    "StandardDeviation": "16.28",
    "classification": "Equity : Small Cap",
    "ExitloadRemarks": "null"
  },
  {
    "Funds": "Mirae Asset Healthcare Fund-Reg(G)",
    "FundManager": "Vrijesh Kasera",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "1269",
    "ExpenseRatio": "2.16",
    "FundType": "Open Ended",
    "InceptionDate": "2-Jul-18",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "19.65",
    "52WeekHigh": "19.88",
    "52WeekLow": "12.67",
    "Return1mo": "5.32",
    "Return3mo": "2.54",
    "Return6mo": "11.23",
    "Return1yr": "55.07",
    "Return2yrs": "35.89",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "37",
    "NoofStocks": "28",
    "AvgMarketCap": "46954",
    "LargeCap": "67.39",
    "MidCap": "29.37",
    "SmallCap": "2.38",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "31.58",
    "Sharpe": "2.56",
    "Sortino": "4.58",
    "Beta": "0.35",
    "StandardDeviation": "19.11",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 1Y(365D) Nil after 1Y(365D)."
  },
  {
    "Funds": "Nippon India Japan Equity Fund(G)",
    "FundManager": "Kinjal Desai",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "136.5",
    "ExpenseRatio": "2.23",
    "FundType": "Open Ended",
    "InceptionDate": "26-Aug-14",
    "BenchmarkIndex": "TOPIX (Tokyo Stock Price Index)",
    "NAV": "17.09",
    "52WeekHigh": "17.18",
    "52WeekLow": "12.29",
    "Return1mo": "3.09",
    "Return3mo": "2.91",
    "Return6mo": "16.94",
    "Return1yr": "38.93",
    "Return2yrs": "16.14",
    "Return3yrs": "11.11",
    "Return5yrs": "11.07",
    "Return10yrs": "-",
    "TurnoverRatio": "20",
    "NoofStocks": "30",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "21.97",
    "Sharpe": "2.06",
    "Sortino": "3.92",
    "Beta": "0.23",
    "StandardDeviation": "16.39",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 1YNil after 1Y"
  },
  {
    "Funds": "Nippon India Pharma Fund(G)",
    "FundManager": "Sailesh Raj Bhan",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "4261",
    "ExpenseRatio": "1.94",
    "FundType": "Open Ended",
    "InceptionDate": "5-Jun-04",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "261.15",
    "52WeekHigh": "266.74",
    "52WeekLow": "173.67",
    "Return1mo": "5.3",
    "Return3mo": "1",
    "Return6mo": "11.62",
    "Return1yr": "49.97",
    "Return2yrs": "31.52",
    "Return3yrs": "22.91",
    "Return5yrs": "14.26",
    "Return10yrs": "16.6",
    "TurnoverRatio": "55",
    "NoofStocks": "21",
    "AvgMarketCap": "41313",
    "LargeCap": "74.22",
    "MidCap": "14.31",
    "SmallCap": "10.86",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "32.03",
    "Sharpe": "2.39",
    "Sortino": "4.24",
    "Beta": "0.32",
    "StandardDeviation": "20.04",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 1M Nil after 1M"
  },
  {
    "Funds": "Nippon India US Equity Opp Fund(G)",
    "FundManager": "Kinjal Desai",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "337.2",
    "ExpenseRatio": "2.67",
    "FundType": "Open Ended",
    "InceptionDate": "23-Jul-15",
    "BenchmarkIndex": "S&P 500 ",
    "NAV": "24.61",
    "52WeekHigh": "24.61",
    "52WeekLow": "15.84",
    "Return1mo": "7.44",
    "Return3mo": "14.29",
    "Return6mo": "23.36",
    "Return1yr": "54.79",
    "Return2yrs": "26.92",
    "Return3yrs": "25.72",
    "Return5yrs": "20.02",
    "Return10yrs": "-",
    "TurnoverRatio": "37",
    "NoofStocks": "24",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "33.87",
    "Sharpe": "2.17",
    "Sortino": "3.66",
    "Beta": "0.22",
    "StandardDeviation": "20.71",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y"
  },
  {
    "Funds": "Quant Active Fund(G)",
    "FundManager": "Ankit Pande",
    "Category": "EQ-MLC",
    "RupeeVestRating": "4",
    "AUM": "260",
    "ExpenseRatio": "2.48",
    "FundType": "Open Ended",
    "InceptionDate": "20-Mar-01",
    "BenchmarkIndex": "NIFTY 500 - TRI",
    "NAV": "312.8",
    "52WeekHigh": "320.33",
    "52WeekLow": "153.21",
    "Return1mo": "5.72",
    "Return3mo": "11.56",
    "Return6mo": "39.4",
    "Return1yr": "101.78",
    "Return2yrs": "29.37",
    "Return3yrs": "20.37",
    "Return5yrs": "19.86",
    "Return10yrs": "15.47",
    "TurnoverRatio": "489",
    "NoofStocks": "51",
    "AvgMarketCap": "21407",
    "LargeCap": "33.53",
    "MidCap": "30.29",
    "SmallCap": "35.59",
    "HighestSector": "Healthcare",
    "AvgMaturity": "103",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "50.15",
    "Sharpe": "4.3",
    "Sortino": "7.11",
    "Beta": "0.5",
    "StandardDeviation": "17.46",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "Nil"
  },
  {
    "Funds": "Quant Consumption Fund(G)",
    "FundManager": "Ankit Pande",
    "Category": "EQ-POWER",
    "RupeeVestRating": "Unrated",
    "AUM": "7.3",
    "ExpenseRatio": "2.48",
    "FundType": "Open Ended",
    "InceptionDate": "23-Sep-08",
    "BenchmarkIndex": "NIFTY CONSUMPTION - TRI",
    "NAV": "41.17",
    "52WeekHigh": "42.6",
    "52WeekLow": "20.97",
    "Return1mo": "3.8",
    "Return3mo": "8.95",
    "Return6mo": "35.25",
    "Return1yr": "94.25",
    "Return2yrs": "25.26",
    "Return3yrs": "14.68",
    "Return5yrs": "18.95",
    "Return10yrs": "10.29",
    "TurnoverRatio": "713",
    "NoofStocks": "23",
    "AvgMarketCap": "20814",
    "LargeCap": "36.05",
    "MidCap": "29",
    "SmallCap": "36.06",
    "HighestSector": "Technology",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "47.93",
    "Sharpe": "4.23",
    "Sortino": "7.53",
    "Beta": "0.48",
    "StandardDeviation": "16.96",
    "classification": "Equity : Sectoral - Energy / Power",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y"
  },
  {
    "Funds": "Quant Small Cap Fund(G)",
    "FundManager": "Ankit Pande",
    "Category": "EQ-SML",
    "RupeeVestRating": "Unrated",
    "AUM": "170.3",
    "ExpenseRatio": "2.39",
    "FundType": "Open Ended",
    "InceptionDate": "16-Oct-96",
    "BenchmarkIndex": "Nifty Smallcap 250 - TRI",
    "NAV": "88.24",
    "52WeekHigh": "90.61",
    "52WeekLow": "32.87",
    "Return1mo": "7.21",
    "Return3mo": "18.22",
    "Return6mo": "45.17",
    "Return1yr": "163.5",
    "Return2yrs": "29.61",
    "Return3yrs": "19.86",
    "Return5yrs": "14.26",
    "Return10yrs": "11.37",
    "TurnoverRatio": "306",
    "NoofStocks": "40",
    "AvgMarketCap": "4053",
    "LargeCap": "1.7",
    "MidCap": "10.04",
    "SmallCap": "88.1",
    "HighestSector": "Healthcare",
    "AvgMaturity": "3.17",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "79.41",
    "Sharpe": "5.09",
    "Sortino": "9.08",
    "Beta": "0.52",
    "StandardDeviation": "20.67",
    "classification": "Equity : Small Cap",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y"
  },
  {
    "Funds": "Quant Tax Plan(G)",
    "FundManager": "Ankit Pande",
    "Category": "EQ-ELSS",
    "RupeeVestRating": "Unrated",
    "AUM": "106",
    "ExpenseRatio": "2.48",
    "FundType": "Open Ended",
    "InceptionDate": "31-Mar-00",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "NAV": "162.43",
    "52WeekHigh": "168.06",
    "52WeekLow": "76.49",
    "Return1mo": "4.11",
    "Return3mo": "10.01",
    "Return6mo": "40.43",
    "Return1yr": "109.71",
    "Return2yrs": "30.57",
    "Return3yrs": "21.38",
    "Return5yrs": "21.63",
    "Return10yrs": "13.2",
    "TurnoverRatio": "631",
    "NoofStocks": "51",
    "AvgMarketCap": "26157",
    "LargeCap": "38.14",
    "MidCap": "29.5",
    "SmallCap": "33.63",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "55.19",
    "Sharpe": "4.57",
    "Sortino": "7.82",
    "Beta": "0.5",
    "StandardDeviation": "17.57",
    "classification": "Equity : Tax Saving (ELSS)",
    "ExitloadRemarks": "Nil"
  },
  {
    "Funds": "SBI Healthcare Opp Fund-Reg(G)",
    "FundManager": "Tanmaya Desai",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "1564",
    "ExpenseRatio": "2.14",
    "FundType": "Open Ended",
    "InceptionDate": "14-Jul-99",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "201.59",
    "52WeekHigh": "205.54",
    "52WeekLow": "134.15",
    "Return1mo": "3.75",
    "Return3mo": "-0.4",
    "Return6mo": "10.27",
    "Return1yr": "49.5",
    "Return2yrs": "29.27",
    "Return3yrs": "18.89",
    "Return5yrs": "7.79",
    "Return10yrs": "16.3",
    "TurnoverRatio": "52",
    "NoofStocks": "19",
    "AvgMarketCap": "35654",
    "LargeCap": "62.52",
    "MidCap": "16.83",
    "SmallCap": "19.3",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "29.46",
    "Sharpe": "2.32",
    "Sortino": "4.06",
    "Beta": "0.32",
    "StandardDeviation": "19.73",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "0.50% on or before 15D Nil after 15D"
  },
  {
    "Funds": "SBI Magnum Global Fund-Reg(G)",
    "FundManager": "Anup Upadhyay",
    "Category": "EQ-MNC",
    "RupeeVestRating": "Unrated",
    "AUM": "4493.4",
    "ExpenseRatio": "2.05",
    "FundType": "Open Ended",
    "InceptionDate": "30-Sep-94",
    "BenchmarkIndex": "Nifty Free Float Midcap 150",
    "NAV": "229.4",
    "52WeekHigh": "234.62",
    "52WeekLow": "155.79",
    "Return1mo": "0.48",
    "Return3mo": "5.01",
    "Return6mo": "22.4",
    "Return1yr": "44.64",
    "Return2yrs": "16.32",
    "Return3yrs": "8.83",
    "Return5yrs": "11.73",
    "Return10yrs": "15.15",
    "TurnoverRatio": "31",
    "NoofStocks": "37",
    "AvgMarketCap": "36665",
    "LargeCap": "48.28",
    "MidCap": "24.33",
    "SmallCap": "22.1",
    "HighestSector": "FMCG",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "17.56",
    "Sharpe": "2.93",
    "Sortino": "4.99",
    "Beta": "0.42",
    "StandardDeviation": "13.13",
    "classification": "Equity : Thematic - MNC",
    "ExitloadRemarks": "1% on or before 12M Nil after 12M"
  },
  {
    "Funds": "Tata India Pharma & Healthcare Fund-Reg(G)",
    "FundManager": "Meeta Shetty",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "435",
    "ExpenseRatio": "2.63",
    "FundType": "Open Ended",
    "InceptionDate": "28-Dec-15",
    "BenchmarkIndex": "NIFTY PHARMA - TRI",
    "NAV": "15.3",
    "52WeekHigh": "15.55",
    "52WeekLow": "10.6",
    "Return1mo": "4.87",
    "Return3mo": "-0.17",
    "Return6mo": "10.42",
    "Return1yr": "43.42",
    "Return2yrs": "30.1",
    "Return3yrs": "20.72",
    "Return5yrs": "9.81",
    "Return10yrs": "-",
    "TurnoverRatio": "49.14",
    "NoofStocks": "21",
    "AvgMarketCap": "37757",
    "LargeCap": "58.42",
    "MidCap": "26.85",
    "SmallCap": "12.74",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "25.35",
    "Sharpe": "2.14",
    "Sortino": "3.79",
    "Beta": "0.29",
    "StandardDeviation": "18.67",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "0.25% on or before 30D"
  },
  {
    "Funds": "UTI Healthcare Fund-Reg(G)",
    "FundManager": "V. Srivatsa",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "618.1",
    "ExpenseRatio": "2.52",
    "FundType": "Open Ended",
    "InceptionDate": "1-Aug-05",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "144.6",
    "52WeekHigh": "147.05",
    "52WeekLow": "96.91",
    "Return1mo": "4.66",
    "Return3mo": "-0.02",
    "Return6mo": "9.72",
    "Return1yr": "49.1",
    "Return2yrs": "29.85",
    "Return3yrs": "19.87",
    "Return5yrs": "10.45",
    "Return10yrs": "13.7",
    "TurnoverRatio": "65.2",
    "NoofStocks": "26",
    "AvgMarketCap": "32260",
    "LargeCap": "57.11",
    "MidCap": "20.01",
    "SmallCap": "21.25",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "32.13",
    "Sharpe": "2.42",
    "Sortino": "4.26",
    "Beta": "0.28",
    "StandardDeviation": "19.13",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 30D Nil after 30D"
  },
  {
    "Funds": "UTI MNC Fund-Reg(G)",
    "FundManager": "Swati Kulkarni",
    "Category": "EQ-MNC",
    "RupeeVestRating": "Unrated",
    "AUM": "2345.3",
    "ExpenseRatio": "2.07",
    "FundType": "Open Ended",
    "InceptionDate": "14-Oct-98",
    "BenchmarkIndex": "NIFTY MNC - TRI",
    "NAV": "229.75",
    "52WeekHigh": "235.33",
    "52WeekLow": "169.43",
    "Return1mo": "-1.16",
    "Return3mo": "-0.04",
    "Return6mo": "14.16",
    "Return1yr": "33.25",
    "Return2yrs": "8.41",
    "Return3yrs": "5.42",
    "Return5yrs": "9.46",
    "Return10yrs": "14.49",
    "TurnoverRatio": "8.87",
    "NoofStocks": "39",
    "AvgMarketCap": "48372",
    "LargeCap": "47.05",
    "MidCap": "44.59",
    "SmallCap": "8.11",
    "HighestSector": "FMCG",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "7.08",
    "Sharpe": "2.22",
    "Sortino": "3.59",
    "Beta": "0.48",
    "StandardDeviation": "13.94",
    "classification": "Equity : Thematic - MNC",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y"
  },
  {
    "Funds": "Aditya Birla SL CEF-Global Agri-Reg(G)",
    "FundManager": "Milind Bafna",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "9.8",
    "ExpenseRatio": "1.73",
    "FundType": "Open Ended",
    "InceptionDate": "7-Nov-08",
    "BenchmarkIndex": "S&P Global Agribusiness Index",
    "NAV": "30.78",
    "52WeekHigh": "30.78",
    "52WeekLow": "18.14",
    "Return1mo": "1.88",
    "Return3mo": "13.5",
    "Return6mo": "36.85",
    "Return1yr": "60.45",
    "Return2yrs": "15.02",
    "Return3yrs": "10.55",
    "Return5yrs": "9.01",
    "Return10yrs": "5.8",
    "TurnoverRatio": "4",
    "NoofStocks": "21",
    "AvgMarketCap": "11480",
    "LargeCap": "3.36",
    "MidCap": "-",
    "SmallCap": "4",
    "HighestSector": "Chemicals",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.41",
    "Sharpe": "2.52",
    "Sortino": "4.38",
    "Beta": "0.25",
    "StandardDeviation": "19.5",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D"
  },
  {
    "Funds": "Aditya Birla SL Intl. Equity Fund-A(G)",
    "FundManager": "Vineet Maloo",
    "Category": "EQ-INTL",
    "RupeeVestRating": "Unrated",
    "AUM": "110.4",
    "ExpenseRatio": "2.5",
    "FundType": "Open Ended",
    "InceptionDate": "31-Oct-07",
    "BenchmarkIndex": "S&P Global 1200",
    "NAV": "29.93",
    "52WeekHigh": "29.93",
    "52WeekLow": "21.16",
    "Return1mo": "7.82",
    "Return3mo": "8.94",
    "Return6mo": "17.99",
    "Return1yr": "40.35",
    "Return2yrs": "19.42",
    "Return3yrs": "17.22",
    "Return5yrs": "13.63",
    "Return10yrs": "11.63",
    "TurnoverRatio": "105",
    "NoofStocks": "70",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "26.46",
    "Sharpe": "2.17",
    "Sortino": "3.51",
    "Beta": "0.16",
    "StandardDeviation": "15.95",
    "classification": "Equity : International",
    "ExitloadRemarks": "1% on or before 90D Nil after 90D"
  },
  {
    "Funds": "Aditya Birla SL Pharma & Healthcare Fund-Reg(G)",
    "FundManager": "Dhaval Shah",
    "Category": "EQ-PHRM",
    "RupeeVestRating": "Unrated",
    "AUM": "454.9",
    "ExpenseRatio": "2.57",
    "FundType": "Open Ended",
    "InceptionDate": "10-Jul-19",
    "BenchmarkIndex": "S&P BSE Health Care - TRI",
    "NAV": "16.78",
    "52WeekHigh": "17.07",
    "52WeekLow": "11.9",
    "Return1mo": "5.2",
    "Return3mo": "0.06",
    "Return6mo": "9.46",
    "Return1yr": "40.18",
    "Return2yrs": "-",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "48",
    "NoofStocks": "25",
    "AvgMarketCap": "43484",
    "LargeCap": "67.4",
    "MidCap": "22.78",
    "SmallCap": "7.63",
    "HighestSector": "Healthcare",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "23.44",
    "Sharpe": "2.14",
    "Sortino": "3.71",
    "Beta": "0.32",
    "StandardDeviation": "18.39",
    "classification": "Equity : Sectoral - Pharma",
    "ExitloadRemarks": "1% on or before 30D Nil after 30D"
  },
  {
    "Funds": "Aditya Birla SL Resurgent India Fund-4-Reg(G)",
    "FundManager": "Chanchal Khandelwal",
    "Category": "EQ-MLC",
    "RupeeVestRating": "Unrated",
    "AUM": "297.1",
    "ExpenseRatio": "-",
    "FundType": "Closed Ended",
    "InceptionDate": "12-Jul-17",
    "BenchmarkIndex": "S&P BSE 200",
    "NAV": "11.21",
    "52WeekHigh": "11.27",
    "52WeekLow": "7.79",
    "Return1mo": "4.09",
    "Return3mo": "19.13",
    "Return6mo": "25.96",
    "Return1yr": "16.29",
    "Return2yrs": "7.31",
    "Return3yrs": "1.56",
    "Return5yrs": "-",
    "Return10yrs": "-",
    "TurnoverRatio": "6",
    "NoofStocks": "46",
    "AvgMarketCap": "84485",
    "LargeCap": "52.16",
    "MidCap": "19.92",
    "SmallCap": "4.86",
    "HighestSector": "Financials",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "3.93",
    "Sharpe": "0.78",
    "Sortino": "1.09",
    "Beta": "0.47",
    "StandardDeviation": "17.97",
    "classification": "Equity : Multi Cap",
    "ExitloadRemarks": "null"
  }
])