%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Funds": "Aditya Birla SL Active Debt Multi-Mgr FoF(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "8.3",
    "ExpenseRatio": "0.64",
    "FundType": "Open Ended",
    "InceptionDate": "28-Dec-06",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "29.05",
    "52WeekHigh": "29.45",
    "52WeekLow": "26.82",
    "Return1mo": "0.95",
    "Return6mo": "2.11",
    "Return1yr": "8.51",
    "Return5yrs": "7.39",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "5.7",
    "Sharpe": "0.9",
    "Sortino": "1.37",
    "Beta": "-",
    "StandardDeviation": "6.39",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Asset Allocator FoF(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "17",
    "ExpenseRatio": "1.35",
    "FundType": "Open Ended",
    "InceptionDate": "17-Aug-06",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "37.51",
    "52WeekHigh": "38.47",
    "52WeekLow": "26.81",
    "Return1mo": "-1.91",
    "Return6mo": "15.02",
    "Return1yr": "37.91",
    "Return5yrs": "11.89",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.46",
    "Sharpe": "3.12",
    "Sortino": "5.07",
    "Beta": "-",
    "StandardDeviation": "11.74",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Aggressive Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "145.8",
    "ExpenseRatio": "0.75",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Hybrid 35+65 - Aggressive Index",
    "NAV": "28.71",
    "52WeekHigh": "29.88",
    "52WeekLow": "20.51",
    "Return1mo": "-2.9",
    "Return6mo": "16.88",
    "Return1yr": "39.97",
    "Return5yrs": "11.85",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "37.3",
    "Sharpe": "2.98",
    "Sortino": "4.92",
    "Beta": "-",
    "StandardDeviation": "12.58",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Conservative Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "13.1",
    "ExpenseRatio": "0.84",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Short Term Debt Hybrid 75+25 Fund Index",
    "NAV": "22.06",
    "52WeekHigh": "22.31",
    "52WeekLow": "18.27",
    "Return1mo": "-0.5",
    "Return6mo": "8.42",
    "Return1yr": "22.19",
    "Return5yrs": "8.2",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "20.16",
    "Sharpe": "3.44",
    "Sortino": "6.08",
    "Beta": "-",
    "StandardDeviation": "5.89",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Moderate Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "24.9",
    "ExpenseRatio": "0.97",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "24.81",
    "52WeekHigh": "25.41",
    "52WeekLow": "19.08",
    "Return1mo": "-1.62",
    "Return6mo": "12.56",
    "Return1yr": "30.72",
    "Return5yrs": "9.87",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "28.65",
    "Sharpe": "3.1",
    "Sortino": "5.14",
    "Beta": "-",
    "StandardDeviation": "9.27",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Axis All Seasons Debt FOFs-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "113",
    "ExpenseRatio": "0.52",
    "FundType": "Open Ended",
    "InceptionDate": "28-Jan-20",
    "BenchmarkIndex": "NIFTY Composite Debt Index",
    "NAV": "11.02",
    "52WeekHigh": "11.02",
    "52WeekLow": "10.08",
    "Return1mo": "0.92",
    "Return6mo": "2.84",
    "Return1yr": "9.46",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "6.4",
    "Sharpe": "3.43",
    "Sortino": "6.22",
    "Beta": "-",
    "StandardDeviation": "1.88",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2023 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "847.1",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "30-Dec-19",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2023",
    "NAV": "11.18",
    "52WeekHigh": "11.19",
    "52WeekLow": "10.17",
    "Return1mo": "0.95",
    "Return6mo": "2.36",
    "Return1yr": "10.07",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "1.95",
    "ModDuration": "1.77",
    "YieldToMaturity": "4.81",
    "Alpha": "6.96",
    "Sharpe": "3.62",
    "Sortino": "6.09",
    "Beta": "-",
    "StandardDeviation": "1.96",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2025 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "1768.1",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "23-Jul-20",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2023",
    "NAV": "10.28",
    "52WeekHigh": "10.33",
    "52WeekLow": "9.86",
    "Return1mo": "1.46",
    "Return6mo": "2.09",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "3.85",
    "ModDuration": "3.26",
    "YieldToMaturity": "5.72",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2030 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "2076.9",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "30-Dec-19",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2030",
    "NAV": "11.45",
    "52WeekHigh": "11.45",
    "52WeekLow": "10.12",
    "Return1mo": "3.47",
    "Return6mo": "3.18",
    "Return1yr": "13.67",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "8.66",
    "ModDuration": "6.14",
    "YieldToMaturity": "6.78",
    "Alpha": "10.33",
    "Sharpe": "2.64",
    "Sortino": "4.98",
    "Beta": "-",
    "StandardDeviation": "3.94",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2031 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "1522.8",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "23-Jul-20",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2031",
    "NAV": "10.28",
    "52WeekHigh": "10.28",
    "52WeekLow": "9.7",
    "Return1mo": "3.4",
    "Return6mo": "2.94",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "9.95",
    "ModDuration": "6.84",
    "YieldToMaturity": "6.82",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Dynamic Asset Allocation FOFs(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "922.5",
    "ExpenseRatio": "1.9",
    "FundType": "Open Ended",
    "InceptionDate": "31-Oct-03",
    "BenchmarkIndex": "CRISIL Hybrid 35+65 - Aggressive Index",
    "NAV": "86.2",
    "52WeekHigh": "87.26",
    "52WeekLow": "60.2",
    "Return1mo": "-0.57",
    "Return6mo": "20.74",
    "Return1yr": "18.28",
    "Return5yrs": "6.62",
    "TurnoverRatio": "74.54",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "19.4",
    "Sharpe": "0.95",
    "Sortino": "1.09",
    "Beta": "-",
    "StandardDeviation": "20.68",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Life Stage FOFs-20(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "12.8",
    "ExpenseRatio": "1.38",
    "FundType": "Open Ended",
    "InceptionDate": "1-Dec-03",
    "BenchmarkIndex": "S&P BSE SENSEX",
    "NAV": "97",
    "52WeekHigh": "103.39",
    "52WeekLow": "61.67",
    "Return1mo": "-4.85",
    "Return6mo": "28.11",
    "Return1yr": "45.74",
    "Return5yrs": "9.54",
    "TurnoverRatio": "5.87",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "43.47",
    "Sharpe": "2.37",
    "Sortino": "3.54",
    "Beta": "-",
    "StandardDeviation": "18.49",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Life Stage FOFs-30(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "5.7",
    "ExpenseRatio": "1.38",
    "FundType": "Open Ended",
    "InceptionDate": "1-Dec-03",
    "BenchmarkIndex": "S&P BSE SENSEX",
    "NAV": "65.63",
    "52WeekHigh": "67.88",
    "52WeekLow": "45.03",
    "Return1mo": "-2.38",
    "Return6mo": "24.48",
    "Return1yr": "25.57",
    "Return5yrs": "7.66",
    "TurnoverRatio": "6.9",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "25.91",
    "Sharpe": "1.38",
    "Sortino": "1.71",
    "Beta": "-",
    "StandardDeviation": "18.99",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Life Stage FOFs-40(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "18.8",
    "ExpenseRatio": "1.43",
    "FundType": "Open Ended",
    "InceptionDate": "1-Dec-03",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "49.26",
    "52WeekHigh": "49.97",
    "52WeekLow": "36.73",
    "Return1mo": "-0.84",
    "Return6mo": "18.82",
    "Return1yr": "10.29",
    "Return5yrs": "5.82",
    "TurnoverRatio": "5.4",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "11.42",
    "Sharpe": "0.57",
    "Sortino": "0.63",
    "Beta": "-",
    "StandardDeviation": "20.32",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Life Stage FOFs-50 Plus(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "17.3",
    "ExpenseRatio": "1.13",
    "FundType": "Open Ended",
    "InceptionDate": "1-Dec-03",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "31.98",
    "52WeekHigh": "34.9",
    "52WeekLow": "25.79",
    "Return1mo": "0.06",
    "Return6mo": "13.48",
    "Return1yr": "-7.13",
    "Return5yrs": "2.64",
    "TurnoverRatio": "5.23",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-5.37",
    "Sharpe": "-0.2",
    "Sortino": "-0.2",
    "Beta": "-",
    "StandardDeviation": "26.31",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Life Stage FOFs-50s +FR(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "20.7",
    "ExpenseRatio": "0.78",
    "FundType": "Open Ended",
    "InceptionDate": "9-Jul-04",
    "BenchmarkIndex": "Crisil Liquid Fund Index",
    "NAV": "43.55",
    "52WeekHigh": "44.21",
    "52WeekLow": "37.92",
    "Return1mo": "-1.17",
    "Return6mo": "7.38",
    "Return1yr": "15",
    "Return5yrs": "7.77",
    "TurnoverRatio": "5.95",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "13.26",
    "Sharpe": "3.06",
    "Sortino": "5.01",
    "Beta": "-",
    "StandardDeviation": "4.36",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Franklin India Multi-Asset Solution Fund(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "39.8",
    "ExpenseRatio": "1.83",
    "FundType": "Open Ended",
    "InceptionDate": "28-Nov-14",
    "BenchmarkIndex": "CRISIL Hybrid 35+65 - Aggressive Index",
    "NAV": "12",
    "52WeekHigh": "12.76",
    "52WeekLow": "9.62",
    "Return1mo": "1.42",
    "Return6mo": "13.82",
    "Return1yr": "-3.34",
    "Return5yrs": "2.82",
    "TurnoverRatio": "40.13",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-1.92",
    "Sharpe": "-0.08",
    "Sortino": "-0.08",
    "Beta": "-",
    "StandardDeviation": "24.36",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "HDFC Dynamic PE Ratio FOF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "19.9",
    "ExpenseRatio": "-",
    "FundType": "Open Ended",
    "InceptionDate": "6-Feb-12",
    "BenchmarkIndex": "NIFTY 50 Hybrid Composite Debt 65:35 Index",
    "NAV": "22.93",
    "52WeekHigh": "23.26",
    "52WeekLow": "16.03",
    "Return1mo": "-0.84",
    "Return6mo": "16.02",
    "Return1yr": "42.1",
    "Return5yrs": "11.41",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "2.95",
    "ModDuration": "2.16",
    "YieldToMaturity": "-",
    "Alpha": "36.19",
    "Sharpe": "3.44",
    "Sortino": "5.55",
    "Beta": "-",
    "StandardDeviation": "10.64",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "HSBC Managed Solutions India-Conservative(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "49.7",
    "ExpenseRatio": "1.6",
    "FundType": "Open Ended",
    "InceptionDate": "30-Apr-14",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "16.71",
    "52WeekHigh": "16.82",
    "52WeekLow": "14.78",
    "Return1mo": "0.42",
    "Return6mo": "2.95",
    "Return1yr": "9.9",
    "Return5yrs": "6.67",
    "TurnoverRatio": "12",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "7.86",
    "Sharpe": "1.22",
    "Sortino": "1.76",
    "Beta": "-",
    "StandardDeviation": "6.51",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "HSBC Managed Solutions India-Growth(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "40.3",
    "ExpenseRatio": "1.82",
    "FundType": "Open Ended",
    "InceptionDate": "30-Apr-14",
    "BenchmarkIndex": "S&P BSE 200",
    "NAV": "22.18",
    "52WeekHigh": "23.5",
    "52WeekLow": "14.45",
    "Return1mo": "-4.43",
    "Return6mo": "18.82",
    "Return1yr": "48.71",
    "Return5yrs": "12.01",
    "TurnoverRatio": "18",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "45.23",
    "Sharpe": "2.94",
    "Sortino": "4.76",
    "Beta": "-",
    "StandardDeviation": "15.54",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "HSBC Managed Solutions India-Moderate(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "68.7",
    "ExpenseRatio": "1.9",
    "FundType": "Open Ended",
    "InceptionDate": "30-Apr-14",
    "BenchmarkIndex": "CRISIL Hybrid 35+65 - Aggressive Index",
    "NAV": "20.88",
    "52WeekHigh": "21.87",
    "52WeekLow": "14.52",
    "Return1mo": "-3.4",
    "Return6mo": "15.36",
    "Return1yr": "39.2",
    "Return5yrs": "10.99",
    "TurnoverRatio": "18",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.94",
    "Sharpe": "2.9",
    "Sortino": "4.7",
    "Beta": "-",
    "StandardDeviation": "12.86",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Asset Allocator Fund(FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "10277.8",
    "ExpenseRatio": "1.37",
    "FundType": "Open Ended",
    "InceptionDate": "18-Dec-03",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "69.09",
    "52WeekHigh": "70.44",
    "52WeekLow": "49.93",
    "Return1mo": "-1.19",
    "Return6mo": "15.14",
    "Return1yr": "36.82",
    "Return5yrs": "12.34",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "2.35",
    "ModDuration": "1.09",
    "YieldToMaturity": "4.6",
    "Alpha": "35.31",
    "Sharpe": "2.93",
    "Sortino": "4.69",
    "Beta": "-",
    "StandardDeviation": "12.08",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Bharat 22 FOF-(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "28.6",
    "ExpenseRatio": "0.01",
    "FundType": "Open Ended",
    "InceptionDate": "29-Jun-18",
    "BenchmarkIndex": "S&P BSE Bharat 22 Index",
    "NAV": "9.99",
    "52WeekHigh": "11.41",
    "52WeekLow": "6.57",
    "Return1mo": "-10.86",
    "Return6mo": "38.17",
    "Return1yr": "42.12",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "22",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "41.45",
    "Sharpe": "1.73",
    "Sortino": "2.8",
    "Beta": "-",
    "StandardDeviation": "24.58",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Debt Mgmt Fund(FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "177.6",
    "ExpenseRatio": "0.25",
    "FundType": "Open Ended",
    "InceptionDate": "18-Dec-03",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "34.46",
    "52WeekHigh": "34.46",
    "52WeekLow": "31.5",
    "Return1mo": "0.81",
    "Return6mo": "2.91",
    "Return1yr": "9.48",
    "Return5yrs": "7.96",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "7.58",
    "Alpha": "6.53",
    "Sharpe": "5.58",
    "Sortino": "10.84",
    "Beta": "-",
    "StandardDeviation": "1.17",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Income Optimizer Fund(FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "302",
    "ExpenseRatio": "1.01",
    "FundType": "Open Ended",
    "InceptionDate": "18-Dec-03",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "40.69",
    "52WeekHigh": "40.94",
    "52WeekLow": "32.99",
    "Return1mo": "0.34",
    "Return6mo": "7.75",
    "Return1yr": "22.67",
    "Return5yrs": "8.05",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "0.23",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "19.76",
    "Sharpe": "4.18",
    "Sortino": "7.31",
    "Beta": "-",
    "StandardDeviation": "4.76",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru India Equity (FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "26.2",
    "ExpenseRatio": "1.09",
    "FundType": "Open Ended",
    "InceptionDate": "25-Feb-20",
    "BenchmarkIndex": "S&P BSE 500 - TRI",
    "NAV": "12.69",
    "52WeekHigh": "13.54",
    "52WeekLow": "7.65",
    "Return1mo": "-5.35",
    "Return6mo": "31.23",
    "Return1yr": "61.52",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "55.59",
    "Sharpe": "3.05",
    "Sortino": "4.9",
    "Beta": "-",
    "StandardDeviation": "18.25",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Passive Strategy Fund(FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "81",
    "ExpenseRatio": "0.43",
    "FundType": "Open Ended",
    "InceptionDate": "18-Dec-03",
    "BenchmarkIndex": "NIFTY 200",
    "NAV": "81.25",
    "52WeekHigh": "84.95",
    "52WeekLow": "49.42",
    "Return1mo": "-3.26",
    "Return6mo": "26.78",
    "Return1yr": "61.23",
    "Return5yrs": "11.43",
    "TurnoverRatio": "8",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "49.95",
    "Sharpe": "3.05",
    "Sortino": "5.04",
    "Beta": "-",
    "StandardDeviation": "16.64",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "ICICI Pru Thematic Advantage Fund(FOF)(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "23.9",
    "ExpenseRatio": "1.57",
    "FundType": "Open Ended",
    "InceptionDate": "18-Dec-03",
    "BenchmarkIndex": "NIFTY 200",
    "NAV": "100.35",
    "52WeekHigh": "106.78",
    "52WeekLow": "58.75",
    "Return1mo": "-4.13",
    "Return6mo": "41.21",
    "Return1yr": "69.66",
    "Return5yrs": "13.48",
    "TurnoverRatio": "43",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "60",
    "Sharpe": "3.08",
    "Sortino": "5.05",
    "Beta": "-",
    "StandardDeviation": "19.38",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "IDFC All Seasons Bond Fund-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "155",
    "ExpenseRatio": "0.49",
    "FundType": "Open Ended",
    "InceptionDate": "13-Sep-04",
    "BenchmarkIndex": "NIFTY AAA Short Duration Bond Index",
    "NAV": "34.37",
    "52WeekHigh": "34.39",
    "52WeekLow": "31.56",
    "Return1mo": "0.92",
    "Return6mo": "1.93",
    "Return1yr": "9.18",
    "Return5yrs": "7.91",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "2.06",
    "ModDuration": "1.8",
    "YieldToMaturity": "4.81",
    "Alpha": "6.15",
    "Sharpe": "3.82",
    "Sortino": "6.9",
    "Beta": "-",
    "StandardDeviation": "1.63",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "IDFC Asset Alloc FoF-Aggr-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "13",
    "ExpenseRatio": "1.29",
    "FundType": "Open Ended",
    "InceptionDate": "11-Feb-10",
    "BenchmarkIndex": "S&P BSE 200",
    "NAV": "26.65",
    "52WeekHigh": "28.04",
    "52WeekLow": "18.87",
    "Return1mo": "-3.44",
    "Return6mo": "11.78",
    "Return1yr": "38.72",
    "Return5yrs": "8.33",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "5.79",
    "ModDuration": "4.13",
    "YieldToMaturity": "7.45",
    "Alpha": "37.2",
    "Sharpe": "2.86",
    "Sortino": "4.54",
    "Beta": "-",
    "StandardDeviation": "13.07",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "IDFC Asset Alloc FoF-Cons-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "8.6",
    "ExpenseRatio": "0.83",
    "FundType": "Open Ended",
    "InceptionDate": "11-Feb-10",
    "BenchmarkIndex": "Crisil Short Term Bond Fund Index",
    "NAV": "24.21",
    "52WeekHigh": "24.57",
    "52WeekLow": "21.33",
    "Return1mo": "-0.76",
    "Return6mo": "3.93",
    "Return1yr": "13.42",
    "Return5yrs": "7.53",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "4.04",
    "ModDuration": "2.9",
    "YieldToMaturity": "7.06",
    "Alpha": "11.84",
    "Sharpe": "3.12",
    "Sortino": "5.15",
    "Beta": "-",
    "StandardDeviation": "3.82",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "IDFC Asset Alloc FoF-Mod-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "16.6",
    "ExpenseRatio": "0.98",
    "FundType": "Open Ended",
    "InceptionDate": "11-Feb-10",
    "BenchmarkIndex": "Crisil Short Term Bond Fund Index",
    "NAV": "25.88",
    "52WeekHigh": "26.81",
    "52WeekLow": "20.94",
    "Return1mo": "-1.93",
    "Return6mo": "7.37",
    "Return1yr": "23.28",
    "Return5yrs": "7.86",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "5.42",
    "ModDuration": "3.88",
    "YieldToMaturity": "7.42",
    "Alpha": "22.13",
    "Sharpe": "2.74",
    "Sortino": "4.24",
    "Beta": "-",
    "StandardDeviation": "8.12",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Kotak Asset Allocator Fund(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "195.2",
    "ExpenseRatio": "0.7",
    "FundType": "Open Ended",
    "InceptionDate": "9-Aug-04",
    "BenchmarkIndex": "NIFTY 50 Hybrid Composite Debt 50:50 Index",
    "NAV": "113.87",
    "52WeekHigh": "116.08",
    "52WeekLow": "77.19",
    "Return1mo": "-0.89",
    "Return6mo": "16.71",
    "Return1yr": "47.28",
    "Return5yrs": "12.93",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "40.98",
    "Sharpe": "3.43",
    "Sortino": "5.34",
    "Beta": "-",
    "StandardDeviation": "12.03",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Mirae Asset Equity Allocator FoF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "96.4",
    "ExpenseRatio": "0.24",
    "FundType": "Open Ended",
    "InceptionDate": "21-Sep-20",
    "BenchmarkIndex": "NIFTY 200 - TRI",
    "NAV": "13.01",
    "52WeekHigh": "13.61",
    "52WeekLow": "9.64",
    "Return1mo": "-3",
    "Return6mo": "24.36",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Mirae Asset ESG Sector Leaders FoF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "106.5",
    "ExpenseRatio": "0.69",
    "FundType": "Open Ended",
    "InceptionDate": "18-Nov-20",
    "BenchmarkIndex": "Nifty 100 ESG Sector Leaders - TRI",
    "NAV": "11.15",
    "52WeekHigh": "11.55",
    "52WeekLow": "9.9",
    "Return1mo": "-1.75",
    "Return6mo": "-",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Motilal Oswal Asset Allocation Passive FoF-Aggressive-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "26.5",
    "ExpenseRatio": "-",
    "FundType": "Open Ended",
    "InceptionDate": "12-Mar-21",
    "BenchmarkIndex": "NIFTY 500 - TRI",
    "NAV": "10.08",
    "52WeekHigh": "10.18",
    "52WeekLow": "9.76",
    "Return1mo": "0.76",
    "Return6mo": "-",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Motilal Oswal Asset Allocation Passive FoF-Conservative-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "32.7",
    "ExpenseRatio": "-",
    "FundType": "Open Ended",
    "InceptionDate": "12-Mar-21",
    "BenchmarkIndex": "Nifty 5 yr Benchmark G-Sec Index TRI",
    "NAV": "10.1",
    "52WeekHigh": "10.17",
    "52WeekLow": "9.89",
    "Return1mo": "1.03",
    "Return6mo": "-",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Nippon India Asset Allocator FoF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "42.5",
    "ExpenseRatio": "1.19",
    "FundType": "Open Ended",
    "InceptionDate": "8-Feb-21",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "10.3",
    "52WeekHigh": "10.53",
    "52WeekLow": "10",
    "Return1mo": "-1.42",
    "Return6mo": "-",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Nippon India Junior BeES FoF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "66.1",
    "ExpenseRatio": "0.28",
    "FundType": "Open Ended",
    "InceptionDate": "8-Mar-19",
    "BenchmarkIndex": "NIFTY NEXT 50",
    "NAV": "12.45",
    "52WeekHigh": "13.09",
    "52WeekLow": "8.28",
    "Return1mo": "-2.3",
    "Return6mo": "24.98",
    "Return1yr": "49.91",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "44.02",
    "Sharpe": "2.69",
    "Sortino": "4.36",
    "Beta": "-",
    "StandardDeviation": "16.58",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Nippon India Passive Flexicap FoF-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "268.3",
    "ExpenseRatio": "0.65",
    "FundType": "Open Ended",
    "InceptionDate": "1-Jan-21",
    "BenchmarkIndex": "NIFTY 500 - TRI",
    "NAV": "10.83",
    "52WeekHigh": "11.26",
    "52WeekLow": "9.87",
    "Return1mo": "-3.2",
    "Return6mo": "-",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Quantum Equity FoF Fund-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "62.1",
    "ExpenseRatio": "0.75",
    "FundType": "Open Ended",
    "InceptionDate": "20-Jul-09",
    "BenchmarkIndex": "S&P BSE 200 - TRI",
    "NAV": "43.98",
    "52WeekHigh": "45.91",
    "52WeekLow": "27.74",
    "Return1mo": "-3.1",
    "Return6mo": "22.76",
    "Return1yr": "55.98",
    "Return5yrs": "12.46",
    "TurnoverRatio": "8.43",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "48.23",
    "Sharpe": "2.9",
    "Sortino": "4.62",
    "Beta": "-",
    "StandardDeviation": "16.78",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Quantum Multi Asset FOFs-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "32.5",
    "ExpenseRatio": "0.47",
    "FundType": "Open Ended",
    "InceptionDate": "11-Jul-12",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "21.96",
    "52WeekHigh": "22.25",
    "52WeekLow": "18.24",
    "Return1mo": "0.16",
    "Return6mo": "5.84",
    "Return1yr": "19.77",
    "Return5yrs": "9.04",
    "TurnoverRatio": "28.52",
    "NoofStocks": "1",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "18.8",
    "Sharpe": "2.63",
    "Sortino": "4.34",
    "Beta": "-",
    "StandardDeviation": "7.18",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Active Debt Multi-Mgr FoF(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "8.3",
    "ExpenseRatio": "0.64",
    "FundType": "Open Ended",
    "InceptionDate": "28-Dec-06",
    "BenchmarkIndex": "Crisil Composite Bond Fund Index",
    "NAV": "29.05",
    "52WeekHigh": "29.45",
    "52WeekLow": "26.82",
    "Return1mo": "0.95",
    "Return6mo": "2.11",
    "Return1yr": "8.51",
    "Return5yrs": "7.39",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "5.7",
    "Sharpe": "0.9",
    "Sortino": "1.37",
    "Beta": "-",
    "StandardDeviation": "6.39",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Asset Allocator FoF(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "17",
    "ExpenseRatio": "1.35",
    "FundType": "Open Ended",
    "InceptionDate": "17-Aug-06",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "37.51",
    "52WeekHigh": "38.47",
    "52WeekLow": "26.81",
    "Return1mo": "-1.91",
    "Return6mo": "15.02",
    "Return1yr": "37.91",
    "Return5yrs": "11.89",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "36.46",
    "Sharpe": "3.12",
    "Sortino": "5.07",
    "Beta": "-",
    "StandardDeviation": "11.74",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Aggressive Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "145.8",
    "ExpenseRatio": "0.75",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Hybrid 35+65 - Aggressive Index",
    "NAV": "28.71",
    "52WeekHigh": "29.88",
    "52WeekLow": "20.51",
    "Return1mo": "-2.9",
    "Return6mo": "16.88",
    "Return1yr": "39.97",
    "Return5yrs": "11.85",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "37.3",
    "Sharpe": "2.98",
    "Sortino": "4.92",
    "Beta": "-",
    "StandardDeviation": "12.58",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Conservative Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "13.1",
    "ExpenseRatio": "0.84",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Short Term Debt Hybrid 75+25 Fund Index",
    "NAV": "22.06",
    "52WeekHigh": "22.31",
    "52WeekLow": "18.27",
    "Return1mo": "-0.5",
    "Return6mo": "8.42",
    "Return1yr": "22.19",
    "Return5yrs": "8.2",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "20.16",
    "Sharpe": "3.44",
    "Sortino": "6.08",
    "Beta": "-",
    "StandardDeviation": "5.89",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Aditya Birla SL Financial Planning FOF Moderate Plan(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "24.9",
    "ExpenseRatio": "0.97",
    "FundType": "Open Ended",
    "InceptionDate": "9-May-11",
    "BenchmarkIndex": "CRISIL Hybrid 50+50 - Moderate Index",
    "NAV": "24.81",
    "52WeekHigh": "25.41",
    "52WeekLow": "19.08",
    "Return1mo": "-1.62",
    "Return6mo": "12.56",
    "Return1yr": "30.72",
    "Return5yrs": "9.87",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "28.65",
    "Sharpe": "3.1",
    "Sortino": "5.14",
    "Beta": "-",
    "StandardDeviation": "9.27",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "Axis All Seasons Debt FOFs-Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "113",
    "ExpenseRatio": "0.52",
    "FundType": "Open Ended",
    "InceptionDate": "28-Jan-20",
    "BenchmarkIndex": "NIFTY Composite Debt Index",
    "NAV": "11.02",
    "52WeekHigh": "11.02",
    "52WeekLow": "10.08",
    "Return1mo": "0.92",
    "Return6mo": "2.84",
    "Return1yr": "9.46",
    "Return5yrs": "-",
    "TurnoverRatio": "-",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "-",
    "ModDuration": "-",
    "YieldToMaturity": "-",
    "Alpha": "6.4",
    "Sharpe": "3.43",
    "Sortino": "6.22",
    "Beta": "-",
    "StandardDeviation": "1.88",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2023 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "847.1",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "30-Dec-19",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2023",
    "NAV": "11.18",
    "52WeekHigh": "11.19",
    "52WeekLow": "10.17",
    "Return1mo": "0.95",
    "Return6mo": "2.36",
    "Return1yr": "10.07",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "1.95",
    "ModDuration": "1.77",
    "YieldToMaturity": "4.81",
    "Alpha": "6.96",
    "Sharpe": "3.62",
    "Sortino": "6.09",
    "Beta": "-",
    "StandardDeviation": "1.96",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2025 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "1768.1",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "23-Jul-20",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2023",
    "NAV": "10.28",
    "52WeekHigh": "10.33",
    "52WeekLow": "9.86",
    "Return1mo": "1.46",
    "Return6mo": "2.09",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "3.85",
    "ModDuration": "3.26",
    "YieldToMaturity": "5.72",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2030 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "2076.9",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "30-Dec-19",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2030",
    "NAV": "11.45",
    "52WeekHigh": "11.45",
    "52WeekLow": "10.12",
    "Return1mo": "3.47",
    "Return6mo": "3.18",
    "Return1yr": "13.67",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "8.66",
    "ModDuration": "6.14",
    "YieldToMaturity": "6.78",
    "Alpha": "10.33",
    "Sharpe": "2.64",
    "Sortino": "4.98",
    "Beta": "-",
    "StandardDeviation": "3.94",
    "classification": "FoFs : Domestic"
  },
  {
    "Funds": "BHARAT Bond FOF - April 2031 -Reg(G)",
    "Category": "FOF-DOM",
    "RupeeVestRating": "Unrated",
    "AUM": "1522.8",
    "ExpenseRatio": "0.05",
    "FundType": "Open Ended",
    "InceptionDate": "23-Jul-20",
    "BenchmarkIndex": "NIFTY BHARAT Bond Index - April 2031",
    "NAV": "10.28",
    "52WeekHigh": "10.28",
    "52WeekLow": "9.7",
    "Return1mo": "3.4",
    "Return6mo": "2.94",
    "Return1yr": "-",
    "Return5yrs": "-",
    "TurnoverRatio": "0",
    "NoofStocks": "-",
    "AvgMarketCap": "-",
    "LargeCap": "-",
    "MidCap": "-",
    "SmallCap": "-",
    "HighestSector": "-",
    "AvgMaturity": "9.95",
    "ModDuration": "6.84",
    "YieldToMaturity": "6.82",
    "Alpha": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Beta": "-",
    "StandardDeviation": "-",
    "classification": "FoFs : Domestic"
  }
])