[
  {
    "InceptionDate": "24-Oct-05",
    "RupeeVestRating": "3",
    "Return10yrs": "12.2",
    "ExpenseRatio": "1.93",
    "YieldToMaturity": "-",
    "Alpha": "3.15",
    "Return1yr": "53.16",
    "NoofStocks": "31",
    "Funds": "Aditya Birla SL Focused Equity Fund(G)",
    "AvgMarketCap": "176217",
    "Return2yrs": "11.39",
    "AvgMaturity": "-",
    "FundManager": "Mahesh Patil",
    "Beta": "0.89",
    "Sharpe": "2.5",
    "Sortino": "4.11",
    "Return1mo": "-3.5",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "74.66",
    "TurnoverRatio": "149",
    "52WeekLow": "47.33",
    "Return3mo": "-2.48",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D",
    "LargeCap": "88.76",
    "Return6mo": "21.68",
    "HighestSector": "Financials",
    "StandardDeviation": "19.11",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "79.16",
    "Return3yrs": "9.79",
    "Return5yrs": "12.41",
    "SmallCap": "1.88",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "4610.5",
    "Category": "EQ-LC",
    "MidCap": "4.94"
  },
  {
    "InceptionDate": "30-Aug-02",
    "RupeeVestRating": "2",
    "Return10yrs": "11.75",
    "ExpenseRatio": "1.7",
    "YieldToMaturity": "-",
    "Alpha": "5.85",
    "Return1yr": "58.77",
    "NoofStocks": "65",
    "Funds": "Aditya Birla SL Frontline Equity Fund(G)",
    "AvgMarketCap": "190227",
    "Return2yrs": "10",
    "AvgMaturity": "-",
    "FundManager": "Mahesh Patil",
    "Beta": "0.9",
    "Sharpe": "2.64",
    "Sortino": "4.27",
    "Return1mo": "-3.69",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "277.5",
    "TurnoverRatio": "74",
    "52WeekLow": "170.35",
    "Return3mo": "-0.71",
    "ExitloadRemarks": "1% on or before 90D Nil after 90D",
    "LargeCap": "85.76",
    "Return6mo": "24.16",
    "HighestSector": "Financials",
    "StandardDeviation": "19.34",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "292.53",
    "Return3yrs": "8.77",
    "Return5yrs": "11.91",
    "SmallCap": "1.66",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "19498.6",
    "Category": "EQ-LC",
    "MidCap": "10.5"
  },
  {
    "InceptionDate": "5-Jan-10",
    "RupeeVestRating": "5",
    "Return10yrs": "13.02",
    "ExpenseRatio": "1.83",
    "YieldToMaturity": "-",
    "Alpha": "-1.23",
    "Return1yr": "43.41",
    "NoofStocks": "33",
    "Funds": "Axis Bluechip Fund-Reg(G)",
    "AvgMarketCap": "338156",
    "Return2yrs": "15.63",
    "AvgMaturity": "-",
    "FundManager": "Shreyash Devalkar",
    "Beta": "0.81",
    "Sharpe": "2.24",
    "Sortino": "3.71",
    "Return1mo": "-3.66",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "38.22",
    "TurnoverRatio": "60",
    "52WeekLow": "25.83",
    "Return3mo": "-2.55",
    "ExitloadRemarks": "Nil for 10% of investments and 1% for remaining investments on or before 12M Nil after 12M",
    "LargeCap": "93.82",
    "Return6mo": "18.73",
    "HighestSector": "Financials",
    "StandardDeviation": "17.62",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "40.83",
    "Return3yrs": "13.88",
    "Return5yrs": "15.48",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "24598.3",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "22-Jun-10",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "6.62",
    "ExpenseRatio": "2.64",
    "YieldToMaturity": "-",
    "Alpha": "1.81",
    "Return1yr": "50.33",
    "NoofStocks": "38",
    "Funds": "Baroda Large Cap Fund(G)",
    "AvgMarketCap": "85936",
    "Return2yrs": "11.48",
    "AvgMaturity": "-",
    "FundManager": "Sanjay Chawla",
    "Beta": "0.87",
    "Sharpe": "2.41",
    "Sortino": "3.9",
    "Return1mo": "-4.9",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "18.25",
    "TurnoverRatio": "96",
    "52WeekLow": "11.8",
    "Return3mo": "-1.99",
    "ExitloadRemarks": "1% on or Before 1Y Nil after 1Y",
    "LargeCap": "80.59",
    "Return6mo": "21.42",
    "HighestSector": "Financials",
    "StandardDeviation": "18.75",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "19.49",
    "Return3yrs": "10.29",
    "Return5yrs": "12.07",
    "SmallCap": "0.05",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "41",
    "Category": "EQ-LC",
    "MidCap": "6.08"
  },
  {
    "InceptionDate": "23-Sep-04",
    "RupeeVestRating": "5",
    "Return10yrs": "12.72",
    "ExpenseRatio": "2.27",
    "YieldToMaturity": "-",
    "Alpha": "-0.03",
    "Return1yr": "48.06",
    "NoofStocks": "42",
    "Funds": "BNP Paribas Large Cap Fund(G)",
    "AvgMarketCap": "271851",
    "Return2yrs": "14.61",
    "AvgMaturity": "-",
    "FundManager": "Karthikraj Lakshmanan",
    "Beta": "0.87",
    "Sharpe": "2.35",
    "Sortino": "3.81",
    "Return1mo": "-4.11",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "116.26",
    "TurnoverRatio": "66",
    "52WeekLow": "76.67",
    "Return3mo": "-2.24",
    "ExitloadRemarks": "Nil upto 10% of Units within 12M 1% exceding 10% of Units within 12M Nil after 12M",
    "LargeCap": "91.48",
    "Return6mo": "19.18",
    "HighestSector": "Financials",
    "StandardDeviation": "18.48",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "124.34",
    "Return3yrs": "11.62",
    "Return5yrs": "12.32",
    "SmallCap": "1.85",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "1027.3",
    "Category": "EQ-LC",
    "MidCap": "5.14"
  },
  {
    "InceptionDate": "20-Aug-10",
    "RupeeVestRating": "5",
    "Return10yrs": "12.51",
    "ExpenseRatio": "2.14",
    "YieldToMaturity": "4.4",
    "Alpha": "5.64",
    "Return1yr": "53.39",
    "NoofStocks": "47",
    "Funds": "Canara Rob Bluechip Equity Fund-Reg(G)",
    "AvgMarketCap": "240529",
    "Return2yrs": "18.04",
    "AvgMaturity": "2.75",
    "FundManager": "Shridatta Bhandwaldar",
    "Beta": "0.83",
    "Sharpe": "2.67",
    "Sortino": "4.4",
    "Return1mo": "-3.13",
    "ModDuration": "2.05",
    "FundType": "Open Ended",
    "NAV": "34.65",
    "TurnoverRatio": "48",
    "52WeekLow": "22.15",
    "Return3mo": "-0.37",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "86.88",
    "Return6mo": "21.32",
    "HighestSector": "Financials",
    "StandardDeviation": "17.67",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "36.66",
    "Return3yrs": "15.13",
    "Return5yrs": "15.64",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "2156.3",
    "Category": "EQ-LC",
    "MidCap": "9.12"
  },
  {
    "InceptionDate": "27-Nov-14",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "-",
    "YieldToMaturity": "-",
    "Alpha": "10.79",
    "Return1yr": "18.34",
    "NoofStocks": "49",
    "Funds": "DSP 3Y Close Ended Equity Fund-Reg(G)",
    "AvgMarketCap": "-",
    "Return2yrs": "15.4",
    "AvgMaturity": "-",
    "FundManager": "Vinit Sambre",
    "Beta": "0.3",
    "Sharpe": "0.76",
    "Sortino": "1.38",
    "Return1mo": "1.43",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "19.08",
    "TurnoverRatio": "-",
    "52WeekLow": "14.45",
    "Return3mo": "17.25",
    "ExitloadRemarks": "null",
    "LargeCap": "-",
    "Return6mo": "23.79",
    "HighestSector": "-",
    "StandardDeviation": "21.94",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "19.15",
    "Return3yrs": "8.75",
    "Return5yrs": "12.09",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 500",
    "AUM": "39.2",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "10-Mar-03",
    "RupeeVestRating": "2",
    "Return10yrs": "9.33",
    "ExpenseRatio": "2.11",
    "YieldToMaturity": "-",
    "Alpha": "2.62",
    "Return1yr": "53.17",
    "NoofStocks": "31",
    "Funds": "DSP Top 100 Equity Fund-Reg(G)",
    "AvgMarketCap": "179759",
    "Return2yrs": "9.51",
    "AvgMaturity": "-",
    "FundManager": "Vinit Sambre",
    "Beta": "0.9",
    "Sharpe": "2.43",
    "Sortino": "3.9",
    "Return1mo": "-2.05",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "250.77",
    "TurnoverRatio": "49",
    "52WeekLow": "158.67",
    "Return3mo": "-1.32",
    "ExitloadRemarks": "1% before 12M Nil on or after 12M",
    "LargeCap": "87.12",
    "Return6mo": "20.75",
    "HighestSector": "Financials",
    "StandardDeviation": "19.66",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "261.38",
    "Return3yrs": "7.67",
    "Return5yrs": "10.85",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "2639.9",
    "Category": "EQ-LC",
    "MidCap": "10.76"
  },
  {
    "InceptionDate": "20-May-09",
    "RupeeVestRating": "4",
    "Return10yrs": "12.19",
    "ExpenseRatio": "2.51",
    "YieldToMaturity": "-",
    "Alpha": "4.13",
    "Return1yr": "55.54",
    "NoofStocks": "61",
    "Funds": "Edelweiss Large Cap Fund(G)",
    "AvgMarketCap": "137095",
    "Return2yrs": "12.46",
    "AvgMaturity": "-",
    "FundManager": "Bharat Lahoti",
    "Beta": "0.86",
    "Sharpe": "2.57",
    "Sortino": "4.12",
    "Return1mo": "-3.32",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "45.45",
    "TurnoverRatio": "319",
    "52WeekLow": "28.39",
    "Return3mo": "-1.35",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D",
    "LargeCap": "78.13",
    "Return6mo": "20.05",
    "HighestSector": "Financials",
    "StandardDeviation": "18.4",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "48.11",
    "Return3yrs": "10.76",
    "Return5yrs": "13.25",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "231.7",
    "Category": "EQ-LC",
    "MidCap": "7.05"
  },
  {
    "InceptionDate": "28-Sep-11",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "2.55",
    "YieldToMaturity": "-",
    "Alpha": "4.51",
    "Return1yr": "55.15",
    "NoofStocks": "56",
    "Funds": "Essel Large Cap Equity Fund(G)",
    "AvgMarketCap": "257518",
    "Return2yrs": "9.78",
    "AvgMaturity": "-",
    "FundManager": "Saravana Kumar",
    "Beta": "0.9",
    "Sharpe": "2.55",
    "Sortino": "4.14",
    "Return1mo": "-4.56",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "28.12",
    "TurnoverRatio": "168",
    "52WeekLow": "17.87",
    "Return3mo": "-1.68",
    "ExitloadRemarks": "Nil",
    "LargeCap": "87.29",
    "Return6mo": "20.51",
    "HighestSector": "Financials",
    "StandardDeviation": "19.39",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "29.9",
    "Return3yrs": "8.06",
    "Return5yrs": "11.38",
    "SmallCap": "1.13",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "95.2",
    "Category": "EQ-LC",
    "MidCap": "5.38"
  },
  {
    "InceptionDate": "1-Dec-93",
    "RupeeVestRating": "1",
    "Return10yrs": "10.16",
    "ExpenseRatio": "1.91",
    "YieldToMaturity": "-",
    "Alpha": "6.58",
    "Return1yr": "60.96",
    "NoofStocks": "27",
    "Funds": "Franklin India Bluechip Fund(G)",
    "AvgMarketCap": "150392",
    "Return2yrs": "10.46",
    "AvgMaturity": "-",
    "FundManager": "Anand Radhakrishnan",
    "Beta": "0.97",
    "Sharpe": "2.43",
    "Sortino": "3.94",
    "Return1mo": "-4.63",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "585.82",
    "TurnoverRatio": "33.57",
    "52WeekLow": "346.35",
    "Return3mo": "2.1",
    "ExitloadRemarks": "1% on or before 1Y",
    "LargeCap": "86.79",
    "Return6mo": "34.15",
    "HighestSector": "Financials",
    "StandardDeviation": "22.61",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "626.03",
    "Return3yrs": "9.66",
    "Return5yrs": "10.91",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "5926.9",
    "Category": "EQ-LC",
    "MidCap": "6.16"
  },
  {
    "InceptionDate": "17-Jul-17",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "-",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Return1yr": "28.78",
    "NoofStocks": "41",
    "Funds": "HDFC Equity Opp Fund-Sr 2-1100D-June 2017(1)-Reg(G)",
    "AvgMarketCap": "229576",
    "Return2yrs": "2",
    "AvgMaturity": "-",
    "FundManager": "Amit Ganatra",
    "Beta": "0.55",
    "Sharpe": "1.94",
    "Sortino": "3.24",
    "Return1mo": "-3.36",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "10.75",
    "TurnoverRatio": "8.94",
    "52WeekLow": "8.07",
    "Return3mo": "-0.2",
    "ExitloadRemarks": "null",
    "LargeCap": "82.64",
    "Return6mo": "19.79",
    "HighestSector": "Financials",
    "StandardDeviation": "14.14",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "11.3",
    "Return3yrs": "3.38",
    "Return5yrs": "-",
    "SmallCap": "2.09",
    "BenchmarkIndex": "NIFTY 50",
    "AUM": "202.2",
    "Category": "EQ-LC",
    "MidCap": "9.88"
  },
  {
    "InceptionDate": "15-Jun-17",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "-",
    "YieldToMaturity": "-",
    "Alpha": "4.13",
    "Return1yr": "37.13",
    "NoofStocks": "40",
    "Funds": "HDFC Equity Opp Fund-Sr 2-1126D-May 2017(1)-Reg(G)",
    "AvgMarketCap": "241395",
    "Return2yrs": "2.03",
    "AvgMaturity": "-",
    "FundManager": "Amit Ganatra",
    "Beta": "0.6",
    "Sharpe": "2.3",
    "Sortino": "3.89",
    "Return1mo": "-2.98",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "11.31",
    "TurnoverRatio": "13.92",
    "52WeekLow": "7.93",
    "Return3mo": "-0.45",
    "ExitloadRemarks": "null",
    "LargeCap": "84.5",
    "Return6mo": "19.07",
    "HighestSector": "Financials",
    "StandardDeviation": "14.93",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "11.87",
    "Return3yrs": "3.24",
    "Return5yrs": "-",
    "SmallCap": "2.15",
    "BenchmarkIndex": "NIFTY 50",
    "AUM": "73.9",
    "Category": "EQ-LC",
    "MidCap": "8.74"
  },
  {
    "InceptionDate": "3-Sep-96",
    "RupeeVestRating": "2",
    "Return10yrs": "9.91",
    "ExpenseRatio": "1.85",
    "YieldToMaturity": "-",
    "Alpha": "1.66",
    "Return1yr": "56.04",
    "NoofStocks": "55",
    "Funds": "HDFC Top 100 Fund(G)",
    "AvgMarketCap": "183646",
    "Return2yrs": "5.1",
    "AvgMaturity": "-",
    "FundManager": "Prashant Jain",
    "Beta": "0.96",
    "Sharpe": "2.35",
    "Sortino": "3.81",
    "Return1mo": "-5.82",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "562.45",
    "TurnoverRatio": "33.35",
    "52WeekLow": "347.88",
    "Return3mo": "-0.4",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "88.72",
    "Return6mo": "28.07",
    "HighestSector": "Financials",
    "StandardDeviation": "21.28",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "609.44",
    "Return3yrs": "8.23",
    "Return5yrs": "12.33",
    "SmallCap": "0.89",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "18660.2",
    "Category": "EQ-LC",
    "MidCap": "8.69"
  },
  {
    "InceptionDate": "10-Dec-02",
    "RupeeVestRating": "3",
    "Return10yrs": "9.55",
    "ExpenseRatio": "2.47",
    "YieldToMaturity": "-",
    "Alpha": "0.83",
    "Return1yr": "53.96",
    "NoofStocks": "28",
    "Funds": "HSBC Large Cap Equity Fund(G)",
    "AvgMarketCap": "340535",
    "Return2yrs": "12.23",
    "AvgMaturity": "-",
    "FundManager": "Neelotpal Sahai",
    "Beta": "0.94",
    "Sharpe": "2.4",
    "Sortino": "3.97",
    "Return1mo": "-4.67",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "266.64",
    "TurnoverRatio": "83",
    "52WeekLow": "168.44",
    "Return3mo": "-2.36",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "97.41",
    "Return6mo": "19.92",
    "HighestSector": "Financials",
    "StandardDeviation": "19.84",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "288.64",
    "Return3yrs": "9.94",
    "Return5yrs": "13.34",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "700.5",
    "Category": "EQ-LC",
    "MidCap": "1.78"
  },
  {
    "InceptionDate": "23-May-08",
    "RupeeVestRating": "3",
    "Return10yrs": "11.9",
    "ExpenseRatio": "1.72",
    "YieldToMaturity": "-",
    "Alpha": "4.51",
    "Return1yr": "56.73",
    "NoofStocks": "63",
    "Funds": "ICICI Pru Bluechip Fund(G)",
    "AvgMarketCap": "229077",
    "Return2yrs": "10.76",
    "AvgMaturity": "-",
    "FundManager": "Anish Tawakley",
    "Beta": "0.91",
    "Sharpe": "2.56",
    "Sortino": "4.17",
    "Return1mo": "-4.37",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "52.77",
    "TurnoverRatio": "24",
    "52WeekLow": "32.91",
    "Return3mo": "-1.09",
    "ExitloadRemarks": "1% on or before 1Y NIL after 1Y",
    "LargeCap": "89.87",
    "Return6mo": "24.22",
    "HighestSector": "Financials",
    "StandardDeviation": "19.55",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "56.02",
    "Return3yrs": "9.7",
    "Return5yrs": "13.47",
    "SmallCap": "0.6",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "26467.8",
    "Category": "EQ-LC",
    "MidCap": "6.61"
  },
  {
    "InceptionDate": "28-May-09",
    "RupeeVestRating": "2",
    "Return10yrs": "10.34",
    "ExpenseRatio": "2.43",
    "YieldToMaturity": "-",
    "Alpha": "15.12",
    "Return1yr": "58.55",
    "NoofStocks": "26",
    "Funds": "ICICI Pru Focused Equity Fund(G)",
    "AvgMarketCap": "124393",
    "Return2yrs": "11.76",
    "AvgMaturity": "-",
    "FundManager": "Prakash Gaurav Goel",
    "Beta": "0.73",
    "Sharpe": "2.83",
    "Sortino": "4.69",
    "Return1mo": "-3.39",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "39.05",
    "TurnoverRatio": "53",
    "52WeekLow": "24.61",
    "Return3mo": "-0.2",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "81.93",
    "Return6mo": "27.57",
    "HighestSector": "Financials",
    "StandardDeviation": "18.2",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "41.14",
    "Return3yrs": "11.29",
    "Return5yrs": "12.47",
    "SmallCap": "8.75",
    "BenchmarkIndex": "S&P BSE 500 - TRI",
    "AUM": "1216.9",
    "Category": "EQ-LC",
    "MidCap": "8.05"
  },
  {
    "InceptionDate": "20-Jun-14",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.42",
    "YieldToMaturity": "-",
    "Alpha": "-5.49",
    "Return1yr": "10.71",
    "NoofStocks": "30",
    "Funds": "ICICI Pru Growth Fund-1(DP)",
    "AvgMarketCap": "-",
    "Return2yrs": "11.34",
    "AvgMaturity": "-",
    "FundManager": "Sankaran Naren",
    "Beta": "0.92",
    "Sharpe": "0.39",
    "Sortino": "0.54",
    "Return1mo": "7.74",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "13.23",
    "TurnoverRatio": "105",
    "52WeekLow": "8.64",
    "Return3mo": "26.72",
    "ExitloadRemarks": "null",
    "LargeCap": "-",
    "Return6mo": "31.9",
    "HighestSector": "-",
    "StandardDeviation": "30.74",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "13.23",
    "Return3yrs": "6.72",
    "Return5yrs": "11.58",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50",
    "AUM": "122.1",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "1-Aug-14",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.41",
    "YieldToMaturity": "-",
    "Alpha": "-2.49",
    "Return1yr": "15.05",
    "NoofStocks": "17",
    "Funds": "ICICI Pru Growth Fund-2(DP)",
    "AvgMarketCap": "181507",
    "Return2yrs": "13.36",
    "AvgMaturity": "-",
    "FundManager": "Mittul Kalawadia",
    "Beta": "0.78",
    "Sharpe": "0.57",
    "Sortino": "0.8",
    "Return1mo": "1.73",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "14.68",
    "TurnoverRatio": "67",
    "52WeekLow": "9.87",
    "Return3mo": "23.99",
    "ExitloadRemarks": "null",
    "LargeCap": "52.04",
    "Return6mo": "26.66",
    "HighestSector": "Technology",
    "StandardDeviation": "26.59",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "15.22",
    "Return3yrs": "9.54",
    "Return5yrs": "14.94",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50",
    "AUM": "59.3",
    "Category": "EQ-LC",
    "MidCap": "4.07"
  },
  {
    "InceptionDate": "18-Apr-17",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.42",
    "YieldToMaturity": "-",
    "Alpha": "-13.1",
    "Return1yr": "2.1",
    "NoofStocks": "5",
    "Funds": "ICICI Pru Value Fund-12(D)",
    "AvgMarketCap": "428200",
    "Return2yrs": "6.68",
    "AvgMaturity": "-",
    "FundManager": "Sankaran Naren",
    "Beta": "0.8",
    "Sharpe": "0.11",
    "Sortino": "0.15",
    "Return1mo": "2.37",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "11.68",
    "TurnoverRatio": "50",
    "52WeekLow": "8.42",
    "Return3mo": "18.7",
    "ExitloadRemarks": "null",
    "LargeCap": "6.44",
    "Return6mo": "20.41",
    "HighestSector": "Financials",
    "StandardDeviation": "26.67",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "11.69",
    "Return3yrs": "3.56",
    "Return5yrs": "-",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE 500",
    "AUM": "773.4",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "15-Jun-17",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.34",
    "YieldToMaturity": "-",
    "Alpha": "-7.81",
    "Return1yr": "11.32",
    "NoofStocks": "24",
    "Funds": "ICICI Pru Value Fund-14(G)",
    "AvgMarketCap": "-",
    "Return2yrs": "11.28",
    "AvgMaturity": "-",
    "FundManager": "Sankaran Naren",
    "Beta": "0.79",
    "Sharpe": "0.43",
    "Sortino": "0.59",
    "Return1mo": "2.31",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "12.39",
    "TurnoverRatio": "43",
    "52WeekLow": "8.31",
    "Return3mo": "17.78",
    "ExitloadRemarks": "null",
    "LargeCap": "-",
    "Return6mo": "23.53",
    "HighestSector": "-",
    "StandardDeviation": "27.51",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "13.02",
    "Return3yrs": "3.98",
    "Return5yrs": "-",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE 500",
    "AUM": "629",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "10-Jan-18",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.37",
    "YieldToMaturity": "-",
    "Alpha": "17.21",
    "Return1yr": "63.17",
    "NoofStocks": "42",
    "Funds": "ICICI Pru Value Fund-19(G)",
    "AvgMarketCap": "87386",
    "Return2yrs": "9.09",
    "AvgMaturity": "-",
    "FundManager": "Sankaran Naren",
    "Beta": "0.8",
    "Sharpe": "2.55",
    "Sortino": "4.4",
    "Return1mo": "-3.48",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "12.76",
    "TurnoverRatio": "71",
    "52WeekLow": "7.77",
    "Return3mo": "5.98",
    "ExitloadRemarks": "null",
    "LargeCap": "77.97",
    "Return6mo": "50.65",
    "HighestSector": "Energy",
    "StandardDeviation": "22.36",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "13.54",
    "Return3yrs": "9.64",
    "Return5yrs": "-",
    "SmallCap": "8.96",
    "BenchmarkIndex": "S&P BSE 500",
    "AUM": "2360.2",
    "Category": "EQ-LC",
    "MidCap": "10.78"
  },
  {
    "InceptionDate": "6-Feb-18",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "1.39",
    "YieldToMaturity": "-",
    "Alpha": "11.29",
    "Return1yr": "57.98",
    "NoofStocks": "43",
    "Funds": "ICICI Pru Value Fund-20(G)",
    "AvgMarketCap": "89231",
    "Return2yrs": "10.24",
    "AvgMaturity": "-",
    "FundManager": "Sankaran Naren",
    "Beta": "0.78",
    "Sharpe": "2.71",
    "Sortino": "4.41",
    "Return1mo": "-1.87",
    "ModDuration": "-",
    "FundType": "Closed Ended",
    "NAV": "12.07",
    "TurnoverRatio": "71",
    "52WeekLow": "7.34",
    "Return3mo": "1.09",
    "ExitloadRemarks": "null",
    "LargeCap": "67.74",
    "Return6mo": "35.16",
    "HighestSector": "Technology",
    "StandardDeviation": "18.54",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "12.55",
    "Return3yrs": "6.64",
    "Return5yrs": "-",
    "SmallCap": "9.94",
    "BenchmarkIndex": "S&P BSE 500",
    "AUM": "628.2",
    "Category": "EQ-LC",
    "MidCap": "16.31"
  },
  {
    "InceptionDate": "17-Nov-17",
    "RupeeVestRating": "2",
    "Return10yrs": "-",
    "ExpenseRatio": "2.47",
    "YieldToMaturity": "-",
    "Alpha": "1.71",
    "Return1yr": "50.62",
    "NoofStocks": "30",
    "Funds": "IDBI Focused 30 Equity Fund-Reg(G)",
    "AvgMarketCap": "227838",
    "Return2yrs": "9.69",
    "AvgMaturity": "-",
    "FundManager": "Uma Venkatraman",
    "Beta": "0.87",
    "Sharpe": "2.43",
    "Sortino": "4",
    "Return1mo": "-3.78",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "12.23",
    "TurnoverRatio": "28",
    "52WeekLow": "7.96",
    "Return3mo": "-1.61",
    "ExitloadRemarks": "1% on or before 12M",
    "LargeCap": "81.96",
    "Return6mo": "19.32",
    "HighestSector": "Financials",
    "StandardDeviation": "18.74",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "12.95",
    "Return3yrs": "7.18",
    "Return5yrs": "-",
    "SmallCap": "5.53",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "136.4",
    "Category": "EQ-LC",
    "MidCap": "8.48"
  },
  {
    "InceptionDate": "15-May-12",
    "RupeeVestRating": "3",
    "Return10yrs": "-",
    "ExpenseRatio": "2.53",
    "YieldToMaturity": "-",
    "Alpha": "3.88",
    "Return1yr": "53.68",
    "NoofStocks": "54",
    "Funds": "IDBI India Top 100 Equity Fund(G)",
    "AvgMarketCap": "201294",
    "Return2yrs": "13.91",
    "AvgMaturity": "-",
    "FundManager": "Uma Venkatraman",
    "Beta": "0.86",
    "Sharpe": "2.56",
    "Sortino": "4.15",
    "Return1mo": "-3.69",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "31.29",
    "TurnoverRatio": "78",
    "52WeekLow": "19.94",
    "Return3mo": "0",
    "ExitloadRemarks": "1% on or before 1YNil after 1Y",
    "LargeCap": "82",
    "Return6mo": "21.28",
    "HighestSector": "Financials",
    "StandardDeviation": "18.37",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "32.93",
    "Return3yrs": "9.69",
    "Return5yrs": "10.97",
    "SmallCap": "2.62",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "426.6",
    "Category": "EQ-LC",
    "MidCap": "14.94"
  },
  {
    "InceptionDate": "9-Jun-06",
    "RupeeVestRating": "3",
    "Return10yrs": "9.27",
    "ExpenseRatio": "2.44",
    "YieldToMaturity": "-",
    "Alpha": "5.22",
    "Return1yr": "52.35",
    "NoofStocks": "39",
    "Funds": "IDFC Large Cap Fund-Reg(G)",
    "AvgMarketCap": "327307",
    "Return2yrs": "11.69",
    "AvgMaturity": "-",
    "FundManager": "Sumit Agrawal",
    "Beta": "0.82",
    "Sharpe": "2.6",
    "Sortino": "4.27",
    "Return1mo": "-3.4",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "40.89",
    "TurnoverRatio": "108",
    "52WeekLow": "26.62",
    "Return3mo": "-2.41",
    "ExitloadRemarks": "Nil",
    "LargeCap": "90.83",
    "Return6mo": "15.93",
    "HighestSector": "Financials",
    "StandardDeviation": "17.81",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "43.81",
    "Return3yrs": "9.9",
    "Return5yrs": "12.58",
    "SmallCap": "0.66",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "707.6",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "10-Feb-12",
    "RupeeVestRating": "3",
    "Return10yrs": "-",
    "ExpenseRatio": "2.43",
    "YieldToMaturity": "-",
    "Alpha": "-3.91",
    "Return1yr": "46.58",
    "NoofStocks": "31",
    "Funds": "Indiabulls Blue Chip Fund(G)",
    "AvgMarketCap": "294704",
    "Return2yrs": "6.68",
    "AvgMaturity": "-",
    "FundManager": "Rajeev Desai",
    "Beta": "0.92",
    "Sharpe": "2.13",
    "Sortino": "3.6",
    "Return1mo": "-4.34",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "24.45",
    "TurnoverRatio": "48",
    "52WeekLow": "16.32",
    "Return3mo": "-2.16",
    "ExitloadRemarks": "1% on or before 7D Nil after 7D",
    "LargeCap": "94.31",
    "Return6mo": "17.1",
    "HighestSector": "Financials",
    "StandardDeviation": "19.64",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "26.03",
    "Return3yrs": "6.37",
    "Return5yrs": "10.96",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "113.2",
    "Category": "EQ-LC",
    "MidCap": "3.89"
  },
  {
    "InceptionDate": "21-Aug-09",
    "RupeeVestRating": "3",
    "Return10yrs": "10.55",
    "ExpenseRatio": "2.44",
    "YieldToMaturity": "-",
    "Alpha": "2.34",
    "Return1yr": "48.63",
    "NoofStocks": "32",
    "Funds": "Invesco India Largecap Fund(G)",
    "AvgMarketCap": "177123",
    "Return2yrs": "9.46",
    "AvgMaturity": "-",
    "FundManager": "Amit Nigam",
    "Beta": "0.84",
    "Sharpe": "2.45",
    "Sortino": "4.05",
    "Return1mo": "-4.18",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "34.84",
    "TurnoverRatio": "83",
    "52WeekLow": "23.07",
    "Return3mo": "-1.25",
    "ExitloadRemarks": "Nil ",
    "LargeCap": "78.74",
    "Return6mo": "14.98",
    "HighestSector": "Financials",
    "StandardDeviation": "18.11",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "36.99",
    "Return3yrs": "8.34",
    "Return5yrs": "11.57",
    "SmallCap": "7.74",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "290.7",
    "Category": "EQ-LC",
    "MidCap": "12.53"
  },
  {
    "InceptionDate": "24-Dec-20",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "2.52",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Return1yr": "-",
    "NoofStocks": "34",
    "Funds": "ITI Large Cap Fund-Reg(G)",
    "AvgMarketCap": "216135",
    "Return2yrs": "-",
    "AvgMaturity": "-",
    "FundManager": "George Heber Joseph",
    "Beta": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Return1mo": "-4.43",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "10.54",
    "TurnoverRatio": "-",
    "52WeekLow": "10",
    "Return3mo": "1.1",
    "ExitloadRemarks": "1% on or before 12M Nil after 12M",
    "LargeCap": "94.69",
    "Return6mo": "-",
    "HighestSector": "Financials",
    "StandardDeviation": "-",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "11.26",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "190.4",
    "Category": "EQ-LC",
    "MidCap": "4.31"
  },
  {
    "InceptionDate": "5-Mar-08",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "9.34",
    "ExpenseRatio": "-",
    "YieldToMaturity": "-",
    "Alpha": "-6.8",
    "Return1yr": "43.3",
    "NoofStocks": "11",
    "Funds": "JM Core 11 Fund(G)",
    "AvgMarketCap": "233227",
    "Return2yrs": "2.42",
    "AvgMaturity": "-",
    "FundManager": "Asit Bhandarkar",
    "Beta": "0.97",
    "Sharpe": "1.86",
    "Sortino": "3.01",
    "Return1mo": "-3.29",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "9.9",
    "TurnoverRatio": "21.95",
    "52WeekLow": "6.44",
    "Return3mo": "-3.61",
    "ExitloadRemarks": "1% on or before 60D",
    "LargeCap": "92.4",
    "Return6mo": "25.45",
    "HighestSector": "Financials",
    "StandardDeviation": "22.41",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "10.67",
    "Return3yrs": "4.61",
    "Return5yrs": "12.9",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE SENSEX - TRI",
    "AUM": "47.7",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "1-Apr-95",
    "RupeeVestRating": "4",
    "Return10yrs": "8.25",
    "ExpenseRatio": "-",
    "YieldToMaturity": "-",
    "Alpha": "-0.1",
    "Return1yr": "34.44",
    "NoofStocks": "50",
    "Funds": "JM Large Cap Fund(G)",
    "AvgMarketCap": "290563",
    "Return2yrs": "10.74",
    "AvgMaturity": "-",
    "FundManager": "Asit Bhandarkar",
    "Beta": "0.61",
    "Sharpe": "2.35",
    "Sortino": "3.79",
    "Return1mo": "-2.51",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "82.19",
    "TurnoverRatio": "307.69",
    "52WeekLow": "59.29",
    "Return3mo": "-0.69",
    "ExitloadRemarks": "1% on or before 60D",
    "LargeCap": "81.78",
    "Return6mo": "13.57",
    "HighestSector": "Financials",
    "StandardDeviation": "12.88",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "85.48",
    "Return3yrs": "8.9",
    "Return5yrs": "9.75",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE SENSEX - TRI",
    "AUM": "60.8",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "4-Feb-03",
    "RupeeVestRating": "4",
    "Return10yrs": "11.32",
    "ExpenseRatio": "2.13",
    "YieldToMaturity": "-",
    "Alpha": "9.68",
    "Return1yr": "62.15",
    "NoofStocks": "54",
    "Funds": "Kotak Bluechip Fund(G)",
    "AvgMarketCap": "179507",
    "Return2yrs": "14.41",
    "AvgMaturity": "-",
    "FundManager": "Harish krishnan",
    "Beta": "0.87",
    "Sharpe": "2.88",
    "Sortino": "4.7",
    "Return1mo": "-3.43",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "308.81",
    "TurnoverRatio": "32.35",
    "52WeekLow": "188.47",
    "Return3mo": "0.62",
    "ExitloadRemarks": "Nil upto 10% of investment and 1% for remaining investment on or before 1Y Nil after 1Y",
    "LargeCap": "78.91",
    "Return6mo": "21.64",
    "HighestSector": "Financials",
    "StandardDeviation": "18.43",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "323.22",
    "Return3yrs": "11.71",
    "Return5yrs": "12.97",
    "SmallCap": "0.73",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "2357.3",
    "Category": "EQ-LC",
    "MidCap": "17.65"
  },
  {
    "InceptionDate": "23-Oct-07",
    "RupeeVestRating": "3",
    "Return10yrs": "10.22",
    "ExpenseRatio": "2.54",
    "YieldToMaturity": "-",
    "Alpha": "4.06",
    "Return1yr": "53.24",
    "NoofStocks": "47",
    "Funds": "L&T India Large Cap Fund-Reg(G)",
    "AvgMarketCap": "233173",
    "Return2yrs": "11.15",
    "AvgMaturity": "-",
    "FundManager": "Venugopal Manghat",
    "Beta": "0.85",
    "Sharpe": "2.54",
    "Sortino": "4.12",
    "Return1mo": "-3.02",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "33.95",
    "TurnoverRatio": "41.28",
    "52WeekLow": "21.82",
    "Return3mo": "-0.61",
    "ExitloadRemarks": "Nil upto 10% of units and 1% for above the limits on or before 1Y Nil after 1Y",
    "LargeCap": "89.34",
    "Return6mo": "20.09",
    "HighestSector": "Financials",
    "StandardDeviation": "18.4",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "35.84",
    "Return3yrs": "9.4",
    "Return5yrs": "11.67",
    "SmallCap": "0.45",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "626.2",
    "Category": "EQ-LC",
    "MidCap": "10.02"
  },
  {
    "InceptionDate": "31-Mar-98",
    "RupeeVestRating": "4",
    "Return10yrs": "9.45",
    "ExpenseRatio": "2.72",
    "YieldToMaturity": "-",
    "Alpha": "-2.24",
    "Return1yr": "44.86",
    "NoofStocks": "38",
    "Funds": "LIC MF Large Cap Fund(G)",
    "AvgMarketCap": "304673",
    "Return2yrs": "12.09",
    "AvgMaturity": "-",
    "FundManager": "Yogesh Patil",
    "Beta": "0.85",
    "Sharpe": "2.2",
    "Sortino": "3.67",
    "Return1mo": "-3.6",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "33.38",
    "TurnoverRatio": "27",
    "52WeekLow": "22.39",
    "Return3mo": "-2.26",
    "ExitloadRemarks": "Nil upto 12% on units and 1% on remaining units on or before 12M Nil after 12M",
    "LargeCap": "95.12",
    "Return6mo": "20.24",
    "HighestSector": "Financials",
    "StandardDeviation": "18.27",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "35.72",
    "Return3yrs": "10.25",
    "Return5yrs": "11.71",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "501.6",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "15-Mar-19",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "2.54",
    "YieldToMaturity": "-",
    "Alpha": "5.09",
    "Return1yr": "54.59",
    "NoofStocks": "33",
    "Funds": "Mahindra Manulife Large Cap Pragati Yojana-Reg(G)",
    "AvgMarketCap": "236618",
    "Return2yrs": "11.41",
    "AvgMaturity": "-",
    "FundManager": "V Balasubramanian",
    "Beta": "0.86",
    "Sharpe": "2.59",
    "Sortino": "4.28",
    "Return1mo": "-3.5",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "12.82",
    "TurnoverRatio": "115",
    "52WeekLow": "8.09",
    "Return3mo": "0.3",
    "ExitloadRemarks": "1% upto 1Y Nil after 1Y",
    "LargeCap": "90.6",
    "Return6mo": "25.34",
    "HighestSector": "Financials",
    "StandardDeviation": "18.62",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "13.52",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "107.4",
    "Category": "EQ-LC",
    "MidCap": "6.53"
  },
  {
    "InceptionDate": "4-Apr-08",
    "RupeeVestRating": "4",
    "Return10yrs": "14.32",
    "ExpenseRatio": "1.64",
    "YieldToMaturity": "-",
    "Alpha": "4.46",
    "Return1yr": "58.42",
    "NoofStocks": "55",
    "Funds": "Mirae Asset Large Cap Fund-Reg(G)",
    "AvgMarketCap": "234785",
    "Return2yrs": "11.69",
    "AvgMaturity": "-",
    "FundManager": "Gaurav Misra",
    "Beta": "0.91",
    "Sharpe": "2.57",
    "Sortino": "4.14",
    "Return1mo": "-3.78",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "64.47",
    "TurnoverRatio": "26",
    "52WeekLow": "39.6",
    "Return3mo": "-0.53",
    "ExitloadRemarks": "1% on or before 1Y(365D) Nil after 1Y(365D)",
    "LargeCap": "86.78",
    "Return6mo": "20.43",
    "HighestSector": "Financials",
    "StandardDeviation": "19.42",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "68.19",
    "Return3yrs": "11.54",
    "Return5yrs": "15.3",
    "SmallCap": "1.04",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "23762.4",
    "Category": "EQ-LC",
    "MidCap": "10.93"
  },
  {
    "InceptionDate": "13-May-13",
    "RupeeVestRating": "4",
    "Return10yrs": "-",
    "ExpenseRatio": "2.12",
    "YieldToMaturity": "-",
    "Alpha": "1.59",
    "Return1yr": "49.53",
    "NoofStocks": "22",
    "Funds": "Motilal Oswal Focused 25 Fund-Reg(G)",
    "AvgMarketCap": "165215",
    "Return2yrs": "15.84",
    "AvgMaturity": "-",
    "FundManager": "Siddharth Bothra",
    "Beta": "0.86",
    "Sharpe": "2.37",
    "Sortino": "3.9",
    "Return1mo": "-3.17",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "29.24",
    "TurnoverRatio": "60",
    "52WeekLow": "18.95",
    "Return3mo": "-1.04",
    "ExitloadRemarks": "1% on or before 15D Nil after 15D",
    "LargeCap": "76.37",
    "Return6mo": "21.09",
    "HighestSector": "Financials",
    "StandardDeviation": "18.95",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "31.04",
    "Return3yrs": "11.28",
    "Return5yrs": "14.23",
    "SmallCap": "2.04",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "1618",
    "Category": "EQ-LC",
    "MidCap": "21.12"
  },
  {
    "InceptionDate": "8-Aug-07",
    "RupeeVestRating": "1",
    "Return10yrs": "11.43",
    "ExpenseRatio": "1.8",
    "YieldToMaturity": "-",
    "Alpha": "3.45",
    "Return1yr": "55.83",
    "NoofStocks": "41",
    "Funds": "Nippon India Large Cap Fund(G)",
    "AvgMarketCap": "185832",
    "Return2yrs": "4.71",
    "AvgMaturity": "-",
    "FundManager": "Sailesh Raj Bhan",
    "Beta": "0.94",
    "Sharpe": "2.39",
    "Sortino": "3.81",
    "Return1mo": "-5.41",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "39.59",
    "TurnoverRatio": "94",
    "52WeekLow": "24.03",
    "Return3mo": "-0.41",
    "ExitloadRemarks": "1% on or before 7D Nil after 7D",
    "LargeCap": "82.44",
    "Return6mo": "28.92",
    "HighestSector": "Financials",
    "StandardDeviation": "21.19",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "42.81",
    "Return3yrs": "7.39",
    "Return5yrs": "12.01",
    "SmallCap": "4.9",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "10069.4",
    "Category": "EQ-LC",
    "MidCap": "12.16"
  },
  {
    "InceptionDate": "30-Jan-03",
    "RupeeVestRating": "3",
    "Return10yrs": "10.2",
    "ExpenseRatio": "2.47",
    "YieldToMaturity": "-",
    "Alpha": "5.85",
    "Return1yr": "54.26",
    "NoofStocks": "41",
    "Funds": "PGIM India Large Cap Fund(G)",
    "AvgMarketCap": "230617",
    "Return2yrs": "11.35",
    "AvgMaturity": "-",
    "FundManager": "Alok Agarwal",
    "Beta": "0.82",
    "Sharpe": "2.66",
    "Sortino": "4.36",
    "Return1mo": "-3.53",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "209.29",
    "TurnoverRatio": "209",
    "52WeekLow": "133.76",
    "Return3mo": "-1.62",
    "ExitloadRemarks": "Nil upto 10% of units and 0.50% for remaining units on or before 90D Nil after 90D",
    "LargeCap": "75.02",
    "Return6mo": "19.29",
    "HighestSector": "Financials",
    "StandardDeviation": "17.67",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "219.83",
    "Return3yrs": "9.5",
    "Return5yrs": "11.43",
    "SmallCap": "5.65",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "308.6",
    "Category": "EQ-LC",
    "MidCap": "6.5"
  },
  {
    "InceptionDate": "19-Oct-20",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "2.39",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Return1yr": "-",
    "NoofStocks": "60",
    "Funds": "Principal Large Cap Fund-Reg(G)",
    "AvgMarketCap": "136170",
    "Return2yrs": "-",
    "AvgMaturity": "-",
    "FundManager": "Sudhir Kedia",
    "Beta": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Return1mo": "-2.27",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "12.06",
    "TurnoverRatio": "-",
    "52WeekLow": "9.86",
    "Return3mo": "-0.17",
    "ExitloadRemarks": "Nil upto 24% of units and 1% in excess of 24% on or before 365D Nil after 365D",
    "LargeCap": "77.26",
    "Return6mo": "-",
    "HighestSector": "Financials",
    "StandardDeviation": "-",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "12.63",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "400.4",
    "Category": "EQ-LC",
    "MidCap": "0.56"
  },
  {
    "InceptionDate": "20-Jan-06",
    "RupeeVestRating": "2",
    "Return10yrs": "13.1",
    "ExpenseRatio": "1.8",
    "YieldToMaturity": "-",
    "Alpha": "6.9",
    "Return1yr": "63.18",
    "NoofStocks": "53",
    "Funds": "SBI BlueChip Fund-Reg(G)",
    "AvgMarketCap": "145516",
    "Return2yrs": "12.98",
    "AvgMaturity": "-",
    "FundManager": "Sohini Andani",
    "Beta": "0.94",
    "Sharpe": "2.65",
    "Sortino": "4.29",
    "Return1mo": "-4.1",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "50.96",
    "TurnoverRatio": "15",
    "52WeekLow": "30.43",
    "Return3mo": "0.37",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "87.27",
    "Return6mo": "27.56",
    "HighestSector": "Financials",
    "StandardDeviation": "20.39",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "54.25",
    "Return3yrs": "9.78",
    "Return5yrs": "12.32",
    "SmallCap": "1.5",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "26838.3",
    "Category": "EQ-LC",
    "MidCap": "8.62"
  },
  {
    "InceptionDate": "8-Oct-20",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "-",
    "ExpenseRatio": "2.29",
    "YieldToMaturity": "-",
    "Alpha": "-",
    "Return1yr": "-",
    "NoofStocks": "49",
    "Funds": "Sundaram Bluechip Fund-Reg(G)",
    "AvgMarketCap": "234863",
    "Return2yrs": "-",
    "AvgMaturity": "-",
    "FundManager": "Rahul Baijal",
    "Beta": "-",
    "Sharpe": "-",
    "Sortino": "-",
    "Return1mo": "-3.13",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "12.12",
    "TurnoverRatio": "65",
    "52WeekLow": "9.89",
    "Return3mo": "-0.23",
    "ExitloadRemarks": "Nil upto 25% of units and 1% for remaining units on or before 1Y Nil after 1Y",
    "LargeCap": "85.78",
    "Return6mo": "21.25",
    "HighestSector": "Financials",
    "StandardDeviation": "-",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "12.77",
    "Return3yrs": "-",
    "Return5yrs": "-",
    "SmallCap": "0.88",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "982.5",
    "Category": "EQ-LC",
    "MidCap": "8.36"
  },
  {
    "InceptionDate": "30-Jul-02",
    "RupeeVestRating": "4",
    "Return10yrs": "9.51",
    "ExpenseRatio": "2.28",
    "YieldToMaturity": "-",
    "Alpha": "1.56",
    "Return1yr": "49.88",
    "NoofStocks": "30",
    "Funds": "Sundaram Select Focus(G)",
    "AvgMarketCap": "306237",
    "Return2yrs": "11.36",
    "AvgMaturity": "-",
    "FundManager": "Rahul Baijal",
    "Beta": "0.86",
    "Sharpe": "2.42",
    "Sortino": "3.97",
    "Return1mo": "-3.94",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "224.92",
    "TurnoverRatio": "86",
    "52WeekLow": "148.95",
    "Return3mo": "-1.03",
    "ExitloadRemarks": "Nil upto 25% of units and 1% for remaining units of or before 365D Nil after 365D",
    "LargeCap": "91.42",
    "Return6mo": "20.64",
    "HighestSector": "Financials",
    "StandardDeviation": "18.4",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "239.78",
    "Return3yrs": "10.75",
    "Return5yrs": "13.73",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "1217.7",
    "Category": "EQ-LC",
    "MidCap": "5.49"
  },
  {
    "InceptionDate": "7-May-98",
    "RupeeVestRating": "2",
    "Return10yrs": "10.55",
    "ExpenseRatio": "2.43",
    "YieldToMaturity": "-",
    "Alpha": "2.92",
    "Return1yr": "58.59",
    "NoofStocks": "34",
    "Funds": "Tata Large Cap Fund(G)",
    "AvgMarketCap": "255016",
    "Return2yrs": "10.26",
    "AvgMaturity": "-",
    "FundManager": "Amey Sathe",
    "Beta": "0.95",
    "Sharpe": "2.49",
    "Sortino": "4.11",
    "Return1mo": "-4.3",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "269.14",
    "TurnoverRatio": "59.31",
    "52WeekLow": "165",
    "Return3mo": "1.44",
    "ExitloadRemarks": "Nil upto 12% of investments and 1% for remaining investments on or before 365D Nil after 365D",
    "LargeCap": "88.55",
    "Return6mo": "25",
    "HighestSector": "Financials",
    "StandardDeviation": "20.33",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "285.08",
    "Return3yrs": "9.08",
    "Return5yrs": "11.21",
    "SmallCap": "2.02",
    "BenchmarkIndex": "S&P BSE SENSEX - TRI",
    "AUM": "892.4",
    "Category": "EQ-LC",
    "MidCap": "7.1"
  },
  {
    "InceptionDate": "28-Feb-95",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "7.07",
    "ExpenseRatio": "2.62",
    "YieldToMaturity": "-",
    "Alpha": "2.62",
    "Return1yr": "48.84",
    "NoofStocks": "48",
    "Funds": "Taurus Largecap Equity Fund-Reg(G)",
    "AvgMarketCap": "238869",
    "Return2yrs": "7.62",
    "AvgMaturity": "-",
    "FundManager": "Prasanna Pathak",
    "Beta": "0.82",
    "Sharpe": "2.49",
    "Sortino": "4.04",
    "Return1mo": "-2.46",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "87.16",
    "TurnoverRatio": "112",
    "52WeekLow": "58.06",
    "Return3mo": "-1.67",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D",
    "LargeCap": "85.86",
    "Return6mo": "15.86",
    "HighestSector": "Financials",
    "StandardDeviation": "17.62",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "91.77",
    "Return3yrs": "6.65",
    "Return5yrs": "8.96",
    "SmallCap": "6",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "29.2",
    "Category": "EQ-LC",
    "MidCap": "3.77"
  },
  {
    "InceptionDate": "11-May-17",
    "RupeeVestRating": "2",
    "Return10yrs": "-",
    "ExpenseRatio": "2.56",
    "YieldToMaturity": "-",
    "Alpha": "2.04",
    "Return1yr": "54.19",
    "NoofStocks": "52",
    "Funds": "Union Largecap Fund-Reg(G)",
    "AvgMarketCap": "183904",
    "Return2yrs": "10.9",
    "AvgMaturity": "-",
    "FundManager": "Vinay Paharia",
    "Beta": "0.92",
    "Sharpe": "2.48",
    "Sortino": "4.05",
    "Return1mo": "-4.14",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "13.43",
    "TurnoverRatio": "32",
    "52WeekLow": "8.48",
    "Return3mo": "-1.47",
    "ExitloadRemarks": "1% on or before 15D Nil after 15D",
    "LargeCap": "91.93",
    "Return6mo": "20.56",
    "HighestSector": "Financials",
    "StandardDeviation": "19.36",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "14.27",
    "Return3yrs": "8.34",
    "Return5yrs": "-",
    "SmallCap": "0.84",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "184.8",
    "Category": "EQ-LC",
    "MidCap": "3.06"
  },
  {
    "InceptionDate": "3-Aug-05",
    "RupeeVestRating": "4",
    "Return10yrs": "11.03",
    "ExpenseRatio": "1.82",
    "YieldToMaturity": "-",
    "Alpha": "7.06",
    "Return1yr": "58.4",
    "NoofStocks": "48",
    "Funds": "UTI Mastershare-Reg(G)",
    "AvgMarketCap": "163803",
    "Return2yrs": "13.37",
    "AvgMaturity": "-",
    "FundManager": "Swati Kulkarni",
    "Beta": "0.89",
    "Sharpe": "2.7",
    "Sortino": "4.41",
    "Return1mo": "-2.54",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "159.58",
    "TurnoverRatio": "11.28",
    "52WeekLow": "98.35",
    "Return3mo": "-0.14",
    "ExitloadRemarks": "Nil upto 10% of units and 1% for remaning units on or before 1Y Nil after 1Y",
    "LargeCap": "86.72",
    "Return6mo": "23.52",
    "HighestSector": "Financials",
    "StandardDeviation": "19.02",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "167.05",
    "Return3yrs": "11.16",
    "Return5yrs": "13.13",
    "SmallCap": "5.11",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "7739.1",
    "Category": "EQ-LC",
    "MidCap": "6.12"
  },
  {
    "InceptionDate": "24-Oct-05",
    "RupeeVestRating": "3",
    "Return10yrs": "12.2",
    "ExpenseRatio": "1.93",
    "YieldToMaturity": "-",
    "Alpha": "3.15",
    "Return1yr": "53.16",
    "NoofStocks": "31",
    "Funds": "Aditya Birla SL Focused Equity Fund(G)",
    "AvgMarketCap": "176217",
    "Return2yrs": "11.39",
    "AvgMaturity": "-",
    "FundManager": "Mahesh Patil",
    "Beta": "0.89",
    "Sharpe": "2.5",
    "Sortino": "4.11",
    "Return1mo": "-3.5",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "74.66",
    "TurnoverRatio": "149",
    "52WeekLow": "47.33",
    "Return3mo": "-2.48",
    "ExitloadRemarks": "1% on or before 365D Nil after 365D",
    "LargeCap": "88.76",
    "Return6mo": "21.68",
    "HighestSector": "Financials",
    "StandardDeviation": "19.11",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "79.16",
    "Return3yrs": "9.79",
    "Return5yrs": "12.41",
    "SmallCap": "1.88",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "4610.5",
    "Category": "EQ-LC",
    "MidCap": "4.94"
  },
  {
    "InceptionDate": "30-Aug-02",
    "RupeeVestRating": "2",
    "Return10yrs": "11.75",
    "ExpenseRatio": "1.7",
    "YieldToMaturity": "-",
    "Alpha": "5.85",
    "Return1yr": "58.77",
    "NoofStocks": "65",
    "Funds": "Aditya Birla SL Frontline Equity Fund(G)",
    "AvgMarketCap": "190227",
    "Return2yrs": "10",
    "AvgMaturity": "-",
    "FundManager": "Mahesh Patil",
    "Beta": "0.9",
    "Sharpe": "2.64",
    "Sortino": "4.27",
    "Return1mo": "-3.69",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "277.5",
    "TurnoverRatio": "74",
    "52WeekLow": "170.35",
    "Return3mo": "-0.71",
    "ExitloadRemarks": "1% on or before 90D Nil after 90D",
    "LargeCap": "85.76",
    "Return6mo": "24.16",
    "HighestSector": "Financials",
    "StandardDeviation": "19.34",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "292.53",
    "Return3yrs": "8.77",
    "Return5yrs": "11.91",
    "SmallCap": "1.66",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "19498.6",
    "Category": "EQ-LC",
    "MidCap": "10.5"
  },
  {
    "InceptionDate": "5-Jan-10",
    "RupeeVestRating": "5",
    "Return10yrs": "13.02",
    "ExpenseRatio": "1.83",
    "YieldToMaturity": "-",
    "Alpha": "-1.23",
    "Return1yr": "43.41",
    "NoofStocks": "33",
    "Funds": "Axis Bluechip Fund-Reg(G)",
    "AvgMarketCap": "338156",
    "Return2yrs": "15.63",
    "AvgMaturity": "-",
    "FundManager": "Shreyash Devalkar",
    "Beta": "0.81",
    "Sharpe": "2.24",
    "Sortino": "3.71",
    "Return1mo": "-3.66",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "38.22",
    "TurnoverRatio": "60",
    "52WeekLow": "25.83",
    "Return3mo": "-2.55",
    "ExitloadRemarks": "Nil for 10% of investments and 1% for remaining investments on or before 12M Nil after 12M",
    "LargeCap": "93.82",
    "Return6mo": "18.73",
    "HighestSector": "Financials",
    "StandardDeviation": "17.62",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "40.83",
    "Return3yrs": "13.88",
    "Return5yrs": "15.48",
    "SmallCap": "-",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "24598.3",
    "Category": "EQ-LC",
    "MidCap": "-"
  },
  {
    "InceptionDate": "22-Jun-10",
    "RupeeVestRating": "Unrated",
    "Return10yrs": "6.62",
    "ExpenseRatio": "2.64",
    "YieldToMaturity": "-",
    "Alpha": "1.81",
    "Return1yr": "50.33",
    "NoofStocks": "38",
    "Funds": "Baroda Large Cap Fund(G)",
    "AvgMarketCap": "85936",
    "Return2yrs": "11.48",
    "AvgMaturity": "-",
    "FundManager": "Sanjay Chawla",
    "Beta": "0.87",
    "Sharpe": "2.41",
    "Sortino": "3.9",
    "Return1mo": "-4.9",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "18.25",
    "TurnoverRatio": "96",
    "52WeekLow": "11.8",
    "Return3mo": "-1.99",
    "ExitloadRemarks": "1% on or Before 1Y Nil after 1Y",
    "LargeCap": "80.59",
    "Return6mo": "21.42",
    "HighestSector": "Financials",
    "StandardDeviation": "18.75",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "19.49",
    "Return3yrs": "10.29",
    "Return5yrs": "12.07",
    "SmallCap": "0.05",
    "BenchmarkIndex": "NIFTY 100 - TRI",
    "AUM": "41",
    "Category": "EQ-LC",
    "MidCap": "6.08"
  },
  {
    "InceptionDate": "23-Sep-04",
    "RupeeVestRating": "5",
    "Return10yrs": "12.72",
    "ExpenseRatio": "2.27",
    "YieldToMaturity": "-",
    "Alpha": "-0.03",
    "Return1yr": "48.06",
    "NoofStocks": "42",
    "Funds": "BNP Paribas Large Cap Fund(G)",
    "AvgMarketCap": "271851",
    "Return2yrs": "14.61",
    "AvgMaturity": "-",
    "FundManager": "Karthikraj Lakshmanan",
    "Beta": "0.87",
    "Sharpe": "2.35",
    "Sortino": "3.81",
    "Return1mo": "-4.11",
    "ModDuration": "-",
    "FundType": "Open Ended",
    "NAV": "116.26",
    "TurnoverRatio": "66",
    "52WeekLow": "76.67",
    "Return3mo": "-2.24",
    "ExitloadRemarks": "Nil upto 10% of Units within 12M 1% exceding 10% of Units within 12M Nil after 12M",
    "LargeCap": "91.48",
    "Return6mo": "19.18",
    "HighestSector": "Financials",
    "StandardDeviation": "18.48",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "124.34",
    "Return3yrs": "11.62",
    "Return5yrs": "12.32",
    "SmallCap": "1.85",
    "BenchmarkIndex": "NIFTY 50 - TRI",
    "AUM": "1027.3",
    "Category": "EQ-LC",
    "MidCap": "5.14"
  },
  {
    "InceptionDate": "20-Aug-10",
    "RupeeVestRating": "5",
    "Return10yrs": "12.51",
    "ExpenseRatio": "2.14",
    "YieldToMaturity": "4.4",
    "Alpha": "5.64",
    "Return1yr": "53.39",
    "NoofStocks": "47",
    "Funds": "Canara Rob Bluechip Equity Fund-Reg(G)",
    "AvgMarketCap": "240529",
    "Return2yrs": "18.04",
    "AvgMaturity": "2.75",
    "FundManager": "Shridatta Bhandwaldar",
    "Beta": "0.83",
    "Sharpe": "2.67",
    "Sortino": "4.4",
    "Return1mo": "-3.13",
    "ModDuration": "2.05",
    "FundType": "Open Ended",
    "NAV": "34.65",
    "TurnoverRatio": "48",
    "52WeekLow": "22.15",
    "Return3mo": "-0.37",
    "ExitloadRemarks": "1% on or before 1Y Nil after 1Y",
    "LargeCap": "86.88",
    "Return6mo": "21.32",
    "HighestSector": "Financials",
    "StandardDeviation": "17.67",
    "classification": "Equity : Large Cap",
    "52WeekHigh": "36.66",
    "Return3yrs": "15.13",
    "Return5yrs": "15.64",
    "SmallCap": "-",
    "BenchmarkIndex": "S&P BSE 100 - TRI",
    "AUM": "2156.3",
    "Category": "EQ-LC",
    "MidCap": "9.12"
  }
]